use squealy::*;
use squealy_postgresql::PostgresConnection;

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct User<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment, db_type = "integer")]
    id: C::Type<'scope, i32>,
    name: C::Type<'scope, String>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct DefaultedRecord<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment, db_type = "integer")]
    id: C::Type<'scope, i32>,
}

#[allow(dead_code)]
#[derive(Schema)]
struct Public {
    users: User<'static, ColumnName>,
}

#[test]
fn postgres_select_uses_numbered_placeholders() {
    let connection = PostgresConnection::default();
    let users = connection.select(|q| {
        let user = q.from::<User>();
        q.where_(user.id.equals(1));
        q.returning(&user.id + 2)
    });

    assert_eq!(
        users.to_sql(),
        "SELECT (q0_0.id + $1) AS expr FROM public.users AS q0_0 WHERE (q0_0.id = $2)"
    );
    assert_eq!(users.params(), vec![BindValue::Int(2), BindValue::Int(1)]);
}

#[test]
fn postgres_select_numbers_placeholders_across_subqueries() {
    let connection = PostgresConnection::default();
    let inner = connection.select(|q| {
        let user = q.from::<User>();
        q.where_(user.name.equals("Ada"));
        q.returning(user.id + 1)
    });
    let outer = connection.select(|q| {
        let user_id = q.q(&inner);
        q.where_(user_id.equals(3));
        q.returning(&user_id + 4)
    });

    assert_eq!(
        outer.to_sql(),
        "SELECT (q0_0.expr + $1) AS expr FROM (SELECT (q0_0.id + $2) AS expr FROM public.users AS q0_0 WHERE (q0_0.name = $3)) AS q0_0 WHERE (q0_0.expr = $4)"
    );
    assert_eq!(
        outer.params(),
        vec![
            BindValue::Int(4),
            BindValue::Int(1),
            BindValue::Text("Ada".to_owned()),
            BindValue::Int(3),
        ]
    );
}

#[test]
fn postgres_insert_update_and_delete_render_returning() {
    let connection = PostgresConnection::default();
    let insert = connection
        .insert::<User>()
        .name("Ada")
        .returning(|user| user.id);
    let update = connection
        .update::<User>()
        .name("Ada")
        .where_(|user| user.id.equals(1))
        .returning(|user| (user.id, user.name));
    let delete = connection
        .delete::<User>()
        .where_(|user| user.id.equals(1))
        .returning(|user| user);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES ($1) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = $1 WHERE (q0_0.id = $2) RETURNING q0_0.id AS t0_id, q0_0.name AS t1_name"
    );
    assert_eq!(
        delete.to_sql(),
        "DELETE FROM public.users AS q0_0 WHERE (q0_0.id = $1) RETURNING q0_0.id AS id, q0_0.name AS name"
    );
    assert_eq!(insert.params(), vec![BindValue::Text("Ada".to_owned())]);
    assert_eq!(
        update.params(),
        vec![BindValue::Text("Ada".to_owned()), BindValue::Int(1)]
    );
    assert_eq!(delete.params(), vec![BindValue::Int(1)]);
}

#[test]
fn postgres_insert_can_use_default_values() {
    let connection = PostgresConnection::default();
    let insert = connection
        .insert::<DefaultedRecord>()
        .returning(|record| record.id);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO defaulted_records DEFAULT VALUES RETURNING q0_0.id AS id"
    );
    assert_eq!(insert.params(), Vec::<BindValue>::new());
}

#[test]
fn postgres_mutation_returning_expressions_continue_placeholder_numbering() {
    let connection = PostgresConnection::default();
    let insert = connection
        .insert::<User>()
        .name("Ada")
        .returning(|user| user.id + 1);
    let update = connection
        .update::<User>()
        .name("Ada")
        .where_(|user| user.id.equals(1))
        .returning(|user| user.id + 2);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES ($1) RETURNING (q0_0.id + $2) AS expr"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = $1 WHERE (q0_0.id = $2) RETURNING (q0_0.id + $3) AS expr"
    );
    assert_eq!(
        insert.params(),
        vec![BindValue::Text("Ada".to_owned()), BindValue::Int(1)]
    );
    assert_eq!(
        update.params(),
        vec![
            BindValue::Text("Ada".to_owned()),
            BindValue::Int(1),
            BindValue::Int(2),
        ]
    );
}

#[test]
fn postgres_backend_writes_table_ddl() {
    let connection = PostgresConnection::default();
    let mut sql = Vec::new();
    let tables = <Public as Schema>::tables().collect::<Vec<_>>();
    connection.write_table(tables[0], &mut sql).unwrap();
    let sql = String::from_utf8(sql).unwrap();

    assert_eq!(
        sql,
        "CREATE TABLE public.users (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text NOT NULL)"
    );
}
