//! Common Table Expressions (`WITH name AS (<body>) …`).
//!
//! A CTE is a **view whose body is inlined** as a `WITH` prefix instead of persisted as a
//! `CREATE VIEW`: a named, read-only, parameter-free query result with typed columns. It is built on
//! the view plumbing ([`ModelConn`](crate::ModelConn) / [`ViewSelect`](crate::ViewSelect) /
//! [`ViewQueryModel`](crate::ViewQueryModel)) — `#[derive(CTE)]` generates the same queryable
//! projection as `#[derive(View)]`, plus the [`SchemaCte`] metadata below.
//!
//! It is **one-directional**: a CTE has no persistent `ViewDef`, and a view is not a
//! [`CteDefinition`] that can be inlined.

use crate::{ModelConn, ViewBody, ViewColumnModel, ViewQueryModel, ViewSelect, ViewSetOp};

/// A CTE's declared output schema — its name and typed columns. The CTE analogue of
/// [`SchemaView`](crate::SchemaView), generated by `#[derive(CTE)]`.
pub trait SchemaCte {
	/// The declared output row type (the ordered column types), matched against the body's projection.
	type Row;

	/// The CTE's name, used as the `WITH` binding and the `FROM` reference.
	fn cte_name() -> &'static str;

	/// The declared output columns (name + type + nullability).
	fn cte_columns() -> Vec<ViewColumnModel>;
}

/// The user-written body of a CTE: the `SELECT` that produces its declared columns, built against the
/// render-only [`ModelConn`] (parameter-free, like a view body). The metadata comes from [`SchemaCte`]
/// (generated by `#[derive(CTE)]`), so the user writes only [`definition`](Self::definition).
///
/// The `impl ViewSelect<Row = <Self as SchemaCte>::Row>` return type is the compile-time guarantee
/// that the body's projection decodes to exactly the declared columns.
pub trait CteDefinition: SchemaCte {
	/// The CTE body, built against the render-only connection (fully owned, no caller lifetime).
	fn definition(db: &'static ModelConn) -> impl ViewSelect<Row = <Self as SchemaCte>::Row>;
}

/// Object-safe view of a CTE used while collecting a query's `WITH` clause: its name and lowered body.
///
pub trait CteDef: Sync {
	fn name(&self) -> &'static str;

	/// A stable per-CTE-type identity, used to de-duplicate a CTE referenced from several sources into
	/// one `WITH` entry and to distinguish that from a genuine name collision between two *distinct*
	/// CTEs. A [`TypeId`](std::any::TypeId) rather than the marker's address: the markers are
	/// zero-sized, and distinct ZST statics are *not* guaranteed distinct addresses.
	fn type_key(&self) -> std::any::TypeId;

	/// The CTE's declared output columns, rendered as the explicit `WITH name (col, …) AS (…)` column
	/// list. Naming the columns explicitly decouples the body's projection aliases from the names the
	/// referencing query uses, so a tuple-projected body still exposes the declared column names.
	fn columns(&self) -> Vec<ViewColumnModel>;

	/// Whether this CTE is recursive (its body is `<anchor> UNION [ALL] <recursive>`). When any CTE in
	/// a query's `WITH` is recursive, the whole clause is rendered `WITH RECURSIVE`.
	fn is_recursive(&self) -> bool {
		false
	}

	/// The CTE's lowered body as a neutral [`ViewBody`] — a plain [`ViewBody::Select`] or, for a
	/// recursive CTE, a [`ViewBody::Set`] union whose recursive arm references this CTE by name. This is
	/// the same representation a `WITH`-prefix in a *view* body carries, so the runtime `WITH` renderer
	/// and the model view renderer share one [`render_with_prefix`](crate::render_with_prefix) path.
	fn body(&self) -> ViewBody;

	/// The CTEs this CTE's body references *directly* (a nested CTE: a `WITH` body that selects from
	/// another CTE). The query's `WITH` collector recurses through these to the transitive closure and
	/// emits every CTE in dependency order (a referenced CTE before the one that uses it). A flat CTE
	/// (body over base tables/views only) returns an empty list.
	fn cte_dependencies(&self) -> Vec<&'static dyn CteDef>;
}

/// Any [`CteDefinition`] is an object-safe [`CteDef`] the `WITH` collector can consume from its type
/// alone. Mirrors the `ViewDef` shim for views.
impl<T> CteDef for T
where
	T: CteDefinition + Sync + 'static,
{
	fn name(&self) -> &'static str {
		<T as SchemaCte>::cte_name()
	}

	fn type_key(&self) -> std::any::TypeId {
		std::any::TypeId::of::<T>()
	}

	fn columns(&self) -> Vec<ViewColumnModel> {
		<T as SchemaCte>::cte_columns()
	}

	fn body(&self) -> ViewBody {
		ViewBody::Select(Box::new(cte_definition_model::<T>()))
	}

	fn cte_dependencies(&self) -> Vec<&'static dyn CteDef> {
		cte_definition_dependencies::<T>()
	}
}

/// Lowers a [`CteDefinition`] type's body into the neutral model without needing an instance. Mirrors
/// [`view_definition_model`](crate::view_definition_model).
pub fn cte_definition_model<T>() -> ViewQueryModel
where
	T: CteDefinition,
{
	static MODEL_CONN: ModelConn = ModelConn;
	T::definition(&MODEL_CONN).lower()
}

/// The CTEs a [`CteDefinition`] type's body references directly, from its type alone — the
/// dependency edges the `WITH` collector follows for nested CTEs. Mirrors [`cte_definition_model`].
pub fn cte_definition_dependencies<T>() -> Vec<&'static dyn CteDef>
where
	T: CteDefinition,
{
	static MODEL_CONN: ModelConn = ModelConn;
	T::definition(&MODEL_CONN).cte_dependencies()
}

// ---------------------------------------------------------------------------
// Recursive CTEs (`WITH RECURSIVE name AS (<anchor> UNION [ALL] <recursive>)`)
// ---------------------------------------------------------------------------

/// The body of a recursive CTE — an anchor term unioned with a recursive term (which references the
/// CTE itself). Built by [`ViewSelect::union_with`] and returned from
/// [`RecursiveCteDefinition::definition`]; lowered to the two neutral models the `WITH RECURSIVE`
/// renderer needs.
pub trait RecursiveBody {
	/// The decoded row type of both arms (matched against the CTE's declared columns).
	type Row;

	/// Lower the anchor and recursive arms into neutral models, in that order.
	fn lower(&self) -> (ViewQueryModel, ViewQueryModel);

	/// The CTEs both arms reference directly (including the recursive self-reference, which the caller
	/// filters out — see [`recursive_cte_definition_dependencies`]).
	fn dependencies(&self) -> Vec<&'static dyn CteDef>;
}

/// A recursive CTE body pairing an anchor [`ViewSelect`] with a recursive one (built by
/// [`ViewSelect::union_with`]). The `UNION` vs `UNION ALL` choice is the CTE's
/// [`RecursiveCteDefinition::UNION_ALL`] const, so it is not carried here.
pub struct RecursiveUnion<Anchor, Recursive> {
	pub(crate) anchor: Anchor,
	pub(crate) recursive: Recursive,
}

impl<Anchor, Recursive> RecursiveBody for RecursiveUnion<Anchor, Recursive>
where
	Anchor: ViewSelect,
	Recursive: ViewSelect<Row = Anchor::Row>,
{
	type Row = Anchor::Row;

	fn lower(&self) -> (ViewQueryModel, ViewQueryModel) {
		(self.anchor.lower(), self.recursive.lower())
	}

	fn dependencies(&self) -> Vec<&'static dyn CteDef> {
		let mut deps = self.anchor.cte_dependencies();
		deps.extend(self.recursive.cte_dependencies());
		deps
	}
}

/// The user-written body of a recursive CTE. `definition` receives the render-only [`ModelConn`] plus a
/// [`RecursiveSelf`](crate::RecursiveSelf) handle for the recursive self-reference, and returns the
/// anchor unioned with the recursive term (`anchor.union_with(step)`). The `impl RecursiveBody<Row =
/// Self::Row>` bound checks both arms decode to the declared columns.
///
/// # SQLite limitation
///
/// Give a recursive arm its own `ORDER BY`/`LIMIT`/`OFFSET` and it can only be scoped by parenthesizing it
/// (`(anchor … LIMIT n) UNION ALL …`). PostgreSQL and MySQL render that; **SQLite's recursive-CTE grammar
/// forbids a parenthesized arm**, so such a shape has no valid SQLite rendering and is rejected at render
/// time. The reject surfaces as a **returned error** from the execution path (`fetch`/`execute`/`prepare`)
/// and from each backend query object's fallible `try_to_sql` — the infallible `to_sql()` still panics on
/// it, as documented on that method. So a recursive CTE with a per-arm `ORDER BY`/`LIMIT`/`OFFSET` remains
/// valid on PostgreSQL and MySQL and returns a render error (rather than panicking) on SQLite.
pub trait RecursiveCteDefinition: SchemaCte {
	/// Whether the recursive union is `UNION ALL` (keeps duplicates) rather than `UNION`.
	const UNION_ALL: bool = false;

	fn definition(
		db: &'static ModelConn,
		recur: crate::RecursiveSelf<'static, Self>,
	) -> impl RecursiveBody<Row = <Self as SchemaCte>::Row>
	where
		Self: Sized;
}

/// Lowers a [`RecursiveCteDefinition`] type's body into a neutral [`ViewBody::Set`] union — `<anchor>
/// UNION [ALL] <recursive>` — from its type alone. The recursive arm references the CTE by name, which is
/// how the shared renderer detects the CTE as recursive (and renders its arms bare). Mirrors
/// [`cte_definition_model`].
pub fn recursive_cte_definition_body<T>() -> ViewBody
where
	T: RecursiveCteDefinition,
{
	static MODEL_CONN: ModelConn = ModelConn;
	let (anchor, recursive) =
		T::definition(&MODEL_CONN, crate::RecursiveSelf::new(&MODEL_CONN)).lower();
	ViewBody::Set {
		op: ViewSetOp::Union,
		all: T::UNION_ALL,
		left: Box::new(ViewBody::Select(Box::new(anchor))),
		right: Box::new(ViewBody::Select(Box::new(recursive))),
		order_by: Vec::new(),
		limit: None,
		offset: None,
	}
}

/// The CTEs a recursive CTE's body references directly, **excluding its own self-reference** (that edge
/// is the recursion, not a dependency). The self-reference is identified by **definition identity** (the
/// CTE's own `CteDef` marker), not by name — so a *different* CTE that merely derives the same bare name
/// is kept and still reaches the collector's normal name-collision check. Mirrors
/// [`cte_definition_dependencies`].
pub fn recursive_cte_definition_dependencies<T>() -> Vec<&'static dyn CteDef>
where
	T: RecursiveCteDefinition + crate::QuerySource,
{
	static MODEL_CONN: ModelConn = ModelConn;
	let own_key = <T as crate::QuerySource>::cte_def().map(|def| def.type_key());
	let mut deps = T::definition(&MODEL_CONN, crate::RecursiveSelf::new(&MODEL_CONN)).dependencies();
	deps.retain(|dep| Some(dep.type_key()) != own_key);
	deps
}
