//! Dialect tests for the in-memory test backend.
//!
//! These pin the test backend's SQL output directly, rather than relying on the
//! incidental assertions in `squealy`'s `derive_metadata.rs`. The notable
//! differences from the PostgreSQL backend are the `?` bind placeholders (vs
//! `$1`, `$2`) and the `AUTOINCREMENT` DDL keyword (vs
//! `GENERATED BY DEFAULT AS IDENTITY`).

use squealy::*;
use squealy_test::{TestBackend, TestConnection, TestParam};

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct User<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    name: C::Type<'scope, String>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct DefaultedRecord<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct Counter<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    count: C::Type<'scope, i32>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct Post<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    user_id: C::Type<'scope, i32>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct Comment<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    post_id: C::Type<'scope, i32>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, ColumnType)]
struct LedgerRef(i32);

// A table with a `ColumnType` newtype column and a nullable column, for subquery kind/nullability
// preservation tests.
#[derive(Clone, Debug, PartialEq, Table)]
struct Event<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    ledger_ref: C::Type<'scope, LedgerRef>,
    label: C::Type<'scope, Option<String>>,
}

// A `Vec<u8>` (bytea) column plus its nullable form — regression coverage for ed37021.
#[derive(Clone, Debug, PartialEq, Table)]
struct Blob<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    data: C::Type<'scope, Vec<u8>>,
    maybe: C::Type<'scope, Option<Vec<u8>>>,
}

// A fixed-size `[u8; N]` column plus its nullable form — coverage for d10dcc0 on the test backend.
#[derive(Clone, Debug, PartialEq, Table)]
struct FixedBlob<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    key: C::Type<'scope, [u8; 4]>,
    nonce: C::Type<'scope, Option<[u8; 2]>>,
}

#[allow(dead_code)]
#[derive(Schema)]
struct Public {
    users: User<'static, ColumnName>,
}

#[test]
fn test_select_uses_question_mark_placeholders() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.equals(1))
        .select(|(user,)| user.id + 2);

    assert_eq!(
        users.to_sql(),
        "SELECT (q0_0.id + ?) AS expr FROM public.users AS q0_0 WHERE (q0_0.id = ?)"
    );
    let mut written = Vec::new();
    users.write_params(&mut written).unwrap();
    assert_eq!(written, vec![TestParam::Int(2), TestParam::Int(1)]);
    assert_eq!(
        users.collect_params().unwrap(),
        vec![TestParam::Int(2), TestParam::Int(1)]
    );
}

#[test]
fn test_runtime_prepared_params_render_without_captured_values() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.name.equals(param::<UserName>()))
        .select(|(user,)| user.name);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.name AS name FROM public.users AS q0_0 WHERE (q0_0.name = ?)"
    );
    assert_eq!(users.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_runtime_prepared_assignment_params_render_without_captured_values() {
    let insert = TestConnection
        .to::<User>()
        .name(param::<UserName>())
        .insert_returning(|user| user.id);
    let update = TestConnection
        .to::<User>()
        .name(param::<UserName>())
        .where_(|user| user.id.equals(param::<UserId>()))
        .update_returning(|user| user.name);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = ? WHERE (q0_0.id = ?) RETURNING q0_0.name AS name"
    );
    assert_eq!(insert.collect_params().unwrap(), Vec::<TestParam>::new());
    assert_eq!(update.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_update_renders_explicit_defaults() {
    let update = TestConnection
        .to::<User>()
        .name(default())
        .where_(|user| user.id.equals(1))
        .update_returning(|user| user.name);

    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = DEFAULT WHERE (q0_0.id = ?) RETURNING q0_0.name AS name"
    );
    assert_eq!(update.collect_params().unwrap(), vec![TestParam::Int(1)]);
}

#[test]
fn test_explicit_update_columns_render_expression_assignments() {
    let update = TestConnection
        .to_columns::<Counter, (CounterCount,)>()
        .set(|counter| (counter.count + 1,))
        .where_(|counter| counter.id.equals(7))
        .update_returning(|counter| counter.count);

    assert_eq!(
        update.to_sql(),
        "UPDATE counters AS q0_0 SET count = (q0_0.count + ?) WHERE (q0_0.id = ?) RETURNING q0_0.count AS count"
    );
    assert_eq!(
        update.collect_params().unwrap(),
        vec![TestParam::Int(1), TestParam::Int(7)]
    );
}

#[test]
fn test_insert_update_and_delete_render_returning() {
    let insert = TestConnection
        .to::<User>()
        .name("Ada")
        .insert_returning(|user| user.id);
    let update = TestConnection
        .to::<User>()
        .name("Ada")
        .where_(|user| user.id.equals(1))
        .update_returning(|user| (user.id, user.name));
    let delete = TestConnection
        .from::<User>()
        .where_(|user| user.id.equals(1))
        .delete_returning(|user| user);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = ? WHERE (q0_0.id = ?) RETURNING q0_0.id AS t0_id, q0_0.name AS t1_name"
    );
    assert_eq!(
        delete.to_sql(),
        "DELETE FROM public.users AS q0_0 WHERE (q0_0.id = ?) RETURNING q0_0.id AS id, q0_0.name AS name"
    );
    assert_eq!(
        insert.collect_params().unwrap(),
        vec![TestParam::Text("Ada".to_owned())]
    );
    assert_eq!(
        update.collect_params().unwrap(),
        vec![TestParam::Text("Ada".to_owned()), TestParam::Int(1)]
    );
    assert_eq!(delete.collect_params().unwrap(), vec![TestParam::Int(1)]);
}

#[test]
fn test_insert_renders_multiple_rows() {
    let insert = TestConnection
        .to_columns::<User, (UserName,)>()
        .row(("Ada",))
        .row(("Grace",))
        .insert_returning(|user| user.id);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (?), (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        insert.collect_params().unwrap(),
        vec![
            TestParam::Text("Ada".to_owned()),
            TestParam::Text("Grace".to_owned())
        ]
    );
}

#[test]
fn test_insert_renders_explicit_defaults() {
    let insert = TestConnection
        .to_columns::<User, (UserName,)>()
        .row((default(),))
        .row(("Grace",))
        .insert_returning(|user| user.id);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (DEFAULT), (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        insert.collect_params().unwrap(),
        vec![TestParam::Text("Grace".to_owned())]
    );
}

#[test]
fn test_insert_can_use_default_values() {
    let insert = TestConnection
        .to::<DefaultedRecord>()
        .insert_returning(|record| record.id);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO defaulted_records DEFAULT VALUES RETURNING q0_0.id AS id"
    );
    assert_eq!(insert.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_queries_can_be_prepared() {
    {
        let select = TestConnection
            .from::<User>()
            .where_(|user| user.id.equals(1))
            .select(|(user,)| user.name);
        let _prepare = select.prepare();
    }

    {
        let insert = TestConnection
            .to::<User>()
            .name("Ada")
            .insert_returning(|user| user.id);
        let _prepare = insert.prepare();
    }

    {
        let update = TestConnection
            .to::<User>()
            .name("Ada")
            .where_(|user| user.id.equals(1))
            .update_returning(|user| user.id);
        let _prepare = update.prepare();
    }

    {
        let delete = TestConnection
            .from::<User>()
            .where_(|user| user.id.equals(1))
            .delete_returning(|user| user.id);
        let _prepare = delete.prepare();
    }
}

#[test]
fn test_runtime_param_queries_can_be_prepared() {
    {
        let select = TestConnection
            .from::<User>()
            .where_(|user| user.name.equals(param::<UserName>()))
            .select(|(user,)| user.id);
        let _prepare = select.prepare();
    }

    {
        let insert = TestConnection
            .to::<User>()
            .name(param::<UserName>())
            .insert_returning(|user| user.id);
        let _prepare = insert.prepare();
    }

    {
        let insert = TestConnection
            .to_columns::<User, (UserName,)>()
            .row((param::<UserName>(),))
            .row((param::<UserName>(),))
            .insert_returning(|user| user.id);
        let _prepare = insert.prepare();
    }

    {
        let update = TestConnection
            .to::<User>()
            .name(param::<UserName>())
            .where_(|user| user.id.equals(param::<UserId>()))
            .update_returning(|user| user.id);
        let _prepare = update.prepare();
    }

    {
        let delete = TestConnection
            .from::<User>()
            .where_(|user| user.id.equals(param::<UserId>()))
            .delete_returning(|user| user.id);
        let _prepare = delete.prepare();
    }
}

#[test]
fn test_backend_writes_table_ddl_with_autoincrement() {
    let mut sql = Vec::new();
    let tables = <Public as Schema>::tables().collect::<Vec<_>>();
    TestBackend.write_table(tables[0], &mut sql).unwrap();
    let sql = String::from_utf8(sql).unwrap();

    assert_eq!(
        sql,
        "CREATE TABLE public.users (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL)"
    );
}

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
#[primary_key(columns = [tenant_id, id])]
struct Seat<'scope, C: ColumnMode = ColumnExpr> {
    tenant_id: C::Type<'scope, i32>,
    id: C::Type<'scope, i32>,
}

#[allow(dead_code)]
#[derive(Schema)]
struct SeatPublic {
    seats: Seat<'static, ColumnName>,
}

#[test]
fn test_backend_writes_compound_primary_key_ddl() {
    // The query-side single-table `write_table` path must also honor a table-level primary key.
    let mut sql = Vec::new();
    let tables = <SeatPublic as Schema>::tables().collect::<Vec<_>>();
    TestBackend.write_table(tables[0], &mut sql).unwrap();
    let sql = String::from_utf8(sql).unwrap();

    assert_eq!(
        sql,
        "CREATE TABLE public.seats (tenant_id integer NOT NULL, id integer NOT NULL, PRIMARY KEY (tenant_id, id))"
    );
}

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct Account<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    nickname: C::Type<'scope, Option<String>>,
}

#[test]
fn test_is_null_renders_is_null() {
    let accounts = TestConnection
        .from::<Account>()
        .where_(|account| account.nickname.is_null())
        .select(|(account,)| account.id);

    assert_eq!(
        accounts.to_sql(),
        "SELECT q0_0.id AS id FROM public.accounts AS q0_0 WHERE (q0_0.nickname IS NULL)"
    );
    assert_eq!(accounts.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_is_not_null_composes_with_other_predicates() {
    let accounts = TestConnection
        .from::<Account>()
        .where_(|account| account.nickname.is_not_null().or(account.id.equals(1)))
        .select(|(account,)| account.id);

    assert_eq!(
        accounts.to_sql(),
        "SELECT q0_0.id AS id FROM public.accounts AS q0_0 WHERE ((q0_0.nickname IS NOT NULL) OR (q0_0.id = ?))"
    );
    assert_eq!(accounts.collect_params().unwrap(), vec![TestParam::Int(1)]);
}

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct Widget<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    name: C::Type<'scope, String>,
    active: C::Type<'scope, bool>,
}

#[test]
fn test_like_renders_pattern_match() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.name.like("A%"))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.name LIKE ?)"
    );
    assert_eq!(
        users.collect_params().unwrap(),
        vec![TestParam::Text("A%".to_owned())]
    );
}

#[test]
fn test_not_like_renders_negated_pattern_match() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.name.not_like("A%"))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.name NOT LIKE ?)"
    );
}

#[test]
fn test_ilike_renders_case_insensitive_pattern_match() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.name.ilike("a%"))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.name ILIKE ?)"
    );
}

#[test]
fn test_in_renders_membership_list() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.in_([1, 2, 3]))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IN (?, ?, ?))"
    );
    assert_eq!(
        users.collect_params().unwrap(),
        vec![TestParam::Int(1), TestParam::Int(2), TestParam::Int(3)]
    );
}

#[test]
fn test_not_in_renders_negated_membership_list() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.not_in([1, 2]))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id NOT IN (?, ?))"
    );
}

#[test]
fn test_empty_in_is_always_false_and_renders_operand() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.in_(Vec::<i32>::new()))
        .select(|(user,)| user.id);

    // The operand is still rendered (so its params stay aligned), guarded by a constant false.
    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IS NOT NULL AND 1 = 0)"
    );
    assert_eq!(users.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_empty_not_in_is_always_true_and_renders_operand() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.not_in(Vec::<i32>::new()))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IS NOT NULL OR 1 = 1)"
    );
}

#[test]
fn test_between_renders_inclusive_range() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.between(1, 10))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id BETWEEN ? AND ?)"
    );
    assert_eq!(
        users.collect_params().unwrap(),
        vec![TestParam::Int(1), TestParam::Int(10)]
    );
}

#[test]
fn test_not_between_renders_negated_range() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.not_between(1, 10))
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id NOT BETWEEN ? AND ?)"
    );
}

#[test]
fn test_bool_column_used_directly_as_predicate() {
    let widgets = TestConnection
        .from::<Widget>()
        .where_(|widget| widget.active.is_true())
        .select(|(widget,)| widget.id);

    assert_eq!(
        widgets.to_sql(),
        "SELECT q0_0.id AS id FROM public.widgets AS q0_0 WHERE (q0_0.active)"
    );
    assert_eq!(widgets.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_bool_column_is_false_negates() {
    let widgets = TestConnection
        .from::<Widget>()
        .where_(|widget| widget.active.is_false())
        .select(|(widget,)| widget.id);

    assert_eq!(
        widgets.to_sql(),
        "SELECT q0_0.id AS id FROM public.widgets AS q0_0 WHERE (NOT q0_0.active)"
    );
}

#[test]
fn test_like_composes_with_in_and_between() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| {
            user.name
                .like("A%")
                .and(user.id.in_([1, 2]))
                .and(user.id.between(1, 100))
        })
        .select(|(user,)| user.id);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 \
         WHERE (((q0_0.name LIKE ?) AND (q0_0.id IN (?, ?))) AND (q0_0.id BETWEEN ? AND ?))"
    );
    assert_eq!(
        users.collect_params().unwrap(),
        vec![
            TestParam::Text("A%".to_owned()),
            TestParam::Int(1),
            TestParam::Int(2),
            TestParam::Int(1),
            TestParam::Int(100),
        ]
    );
}

#[test]
fn test_count_renders_aggregate() {
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.count());
    assert_eq!(
        q.to_sql(),
        "SELECT COUNT(q0_0.id) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_aggregate_select_can_order_by_aggregate() {
    // An aggregate-only projection may order by an aggregate (the order class matches the
    // projection class) — only scalar ordering of an aggregate select is rejected.
    let q = TestConnection
        .from::<User>()
        .order_by(|(user,)| user.id.count().desc())
        .select(|(user,)| user.id.count());
    assert_eq!(
        q.to_sql(),
        "SELECT COUNT(q0_0.id) AS expr FROM public.users AS q0_0 ORDER BY COUNT(q0_0.id) DESC"
    );
}

#[test]
fn test_sum_avg_min_max_render_aggregates() {
    let sum = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.sum());
    assert_eq!(
        sum.to_sql(),
        "SELECT SUM(q0_0.id) AS expr FROM public.users AS q0_0"
    );

    let avg = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.avg());
    assert_eq!(
        avg.to_sql(),
        "SELECT AVG(q0_0.id) AS expr FROM public.users AS q0_0"
    );

    let min = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.min());
    assert_eq!(
        min.to_sql(),
        "SELECT MIN(q0_0.id) AS expr FROM public.users AS q0_0"
    );

    let max = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.max());
    assert_eq!(
        max.to_sql(),
        "SELECT MAX(q0_0.id) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_aggregates_compose_in_a_tuple_with_filter() {
    let q = TestConnection
        .from::<User>()
        .where_(|user| user.id.greater_than(0))
        .select(|(user,)| (user.id.count(), user.id.sum()));
    assert_eq!(
        q.to_sql(),
        "SELECT COUNT(q0_0.id) AS t0_expr, SUM(q0_0.id) AS t1_expr FROM public.users AS q0_0 WHERE (q0_0.id > ?)"
    );
}

/// Compile-time checks that the aggregate result types are nullable (except `COUNT`) and that
/// integer `SUM` widens to `i64`.
#[test]
fn test_aggregate_result_types() {
    let count: <CountExpr<i32> as ExprKind>::Value = 0i64;
    let _: i64 = count;

    // ≤32-bit operands sum to `i64`; 64-bit and wider widen to `i128` to match PostgreSQL's
    // `numeric` result and avoid a narrowing `bigint` cast.
    let sum: <SumExpr<i32> as ExprKind>::Value = Some(0i64);
    let _: Option<i64> = sum;

    let wide_sum: <SumExpr<i64> as ExprKind>::Value = Some(0i128);
    let _: Option<i128> = wide_sum;

    // `u128` keeps an unsigned sum: a single value can exceed `i128::MAX`.
    let unsigned_sum: <SumExpr<u128> as ExprKind>::Value = Some(0u128);
    let _: Option<u128> = unsigned_sum;

    let avg: <AvgExpr<i32> as ExprKind>::Value = Some(0.0f64);
    let _: Option<f64> = avg;

    let min: <MinExpr<i32> as ExprKind>::Value = Some(0i32);
    let _: Option<i32> = min;

    let max: <MaxExpr<String> as ExprKind>::Value = Some(String::new());
    let _: Option<String> = max;
}

/// Exhaustive compile-time check of the `SUM` widening for every numeric operand type. ≤32-bit
/// integers sum to `i64`; 64-bit-and-wider signed/`bigint`-stored operands to `i128`; `u128` stays
/// unsigned (a single value can exceed `i128::MAX`); floats to `f64`. Each is also asserted to be
/// decodable on PostgreSQL by [`sum_result_types_decode_on_postgres`] there.
#[test]
fn test_sum_widening_for_every_numeric_operand() {
    fn sum_is<K, Expected>()
    where
        K: ExprKind,
        SumExpr<K>: ExprKind<Value = Option<Expected>>,
    {
    }

    sum_is::<i8, i64>();
    sum_is::<i16, i64>();
    sum_is::<i32, i64>();
    sum_is::<u8, i64>();
    sum_is::<u16, i64>();

    sum_is::<i64, i128>();
    sum_is::<isize, i128>();
    sum_is::<u32, i128>();
    sum_is::<u64, i128>();
    sum_is::<usize, i128>();
    sum_is::<i128, i128>();

    sum_is::<u128, u128>();

    sum_is::<f32, f64>();
    sum_is::<f64, f64>();
}

/// Compile-time checks that aggregates over a nullable operand kind (`Nullable<K>`, as produced by
/// a `left_join`) unwrap the nullability: `SUM` still widens to `Option<i64>`, and `MIN` stays a
/// single `Option<i32>` rather than nesting a second `Option`.
#[test]
fn test_aggregate_nullable_operand_types_unwrap() {
    let sum: <SumExpr<Nullable<i32>> as ExprKind>::Value = Some(0i64);
    let _: Option<i64> = sum;

    let avg: <AvgExpr<Nullable<i32>> as ExprKind>::Value = Some(0.0f64);
    let _: Option<f64> = avg;

    let min: <MinExpr<Nullable<i32>> as ExprKind>::Value = Some(0i32);
    let _: Option<i32> = min;
}

#[test]
fn test_group_by_allows_mixed_projection() {
    // A grouped query may select a grouping key alongside an aggregate (rejected without GROUP BY).
    let q = TestConnection
        .from::<User>()
        .group_by(|(user,)| user.name)
        .select(|(user,)| (user.name, user.id.count()));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.name AS t0_name, COUNT(q0_0.id) AS t1_expr \
         FROM public.users AS q0_0 GROUP BY q0_0.name"
    );
}

#[test]
fn test_group_by_having_full_clause_order() {
    // WHERE -> GROUP BY (multiple keys) -> HAVING (aggregate) -> ORDER BY, with params in order.
    let q = TestConnection
        .from::<User>()
        .where_(|user| user.id.greater_than(0))
        .group_by(|(user,)| user.id)
        .group_by(|(user,)| user.name)
        .having(|(user,)| user.id.count().greater_than(1i64))
        .order_by(|(user,)| user.name.asc())
        .select(|(user,)| (user.id, user.name, user.id.count()));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_0.name AS t1_name, COUNT(q0_0.id) AS t2_expr \
         FROM public.users AS q0_0 WHERE (q0_0.id > ?) GROUP BY q0_0.id, q0_0.name \
         HAVING (COUNT(q0_0.id) > ?) ORDER BY q0_0.name ASC"
    );
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Int(0), TestParam::Int(1)]
    );
}

#[test]
fn test_grouped_having_allows_grouping_key_predicate() {
    // With a GROUP BY present, a HAVING predicate may reference a grouping key (a bare column) —
    // the database validates it is grouped. Without GROUP BY this would be rejected at compile time.
    let q = TestConnection
        .from::<User>()
        .group_by(|(user,)| user.id)
        .having(|(user,)| user.id.greater_than(0))
        .select(|(user,)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 GROUP BY q0_0.id HAVING (q0_0.id > ?)"
    );
}

#[test]
fn test_having_before_group_by_is_order_independent() {
    // A bare-column HAVING predicate is rescued by a *later* group_by: building `having` before
    // `group_by` compiles and renders identically to the canonical order (the renderer always emits
    // GROUP BY before HAVING). Validation is based on the final chain state, not call order.
    let reversed = TestConnection
        .from::<User>()
        .having(|(user,)| user.id.greater_than(0))
        .group_by(|(user,)| user.id)
        .select(|(user,)| user.id);
    let canonical = TestConnection
        .from::<User>()
        .group_by(|(user,)| user.id)
        .having(|(user,)| user.id.greater_than(0))
        .select(|(user,)| user.id);
    assert_eq!(
        reversed.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 GROUP BY q0_0.id HAVING (q0_0.id > ?)"
    );
    assert_eq!(reversed.to_sql(), canonical.to_sql());
}

#[test]
fn test_whole_table_having_allows_constant_projection() {
    // A whole-table-aggregate query (HAVING, no GROUP BY) may project constants alongside
    // aggregates — they do not depend on an ungrouped row. Only bare columns are rejected there.
    let q = TestConnection
        .from::<User>()
        .having(|(user,)| user.id.count().greater_than(0i64))
        .select(|(user,)| (1, user.id.count()));
    assert_eq!(
        q.to_sql(),
        "SELECT ? AS t0_expr, COUNT(q0_0.id) AS t1_expr \
         FROM public.users AS q0_0 HAVING (COUNT(q0_0.id) > ?)"
    );
}

#[test]
fn test_having_without_group_by_on_whole_table_aggregate() {
    // `HAVING` is valid without `GROUP BY` over a whole-table aggregate, and may use aggregates.
    let q = TestConnection
        .from::<User>()
        .having(|(user,)| user.id.count().greater_than(0i64))
        .select(|(user,)| user.id.count());
    assert_eq!(
        q.to_sql(),
        "SELECT COUNT(q0_0.id) AS expr FROM public.users AS q0_0 HAVING (COUNT(q0_0.id) > ?)"
    );
}

#[test]
fn test_group_by_tuple_matches_chained_keys() {
    // A tuple of keys in one call renders identically to chaining `group_by`.
    let tuple = TestConnection
        .from::<User>()
        .group_by(|(user,)| (user.id, user.name))
        .select(|(user,)| (user.id, user.name, user.id.count()));
    let chained = TestConnection
        .from::<User>()
        .group_by(|(user,)| user.id)
        .group_by(|(user,)| user.name)
        .select(|(user,)| (user.id, user.name, user.id.count()));
    assert_eq!(
        tuple.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_0.name AS t1_name, COUNT(q0_0.id) AS t2_expr \
         FROM public.users AS q0_0 GROUP BY q0_0.id, q0_0.name"
    );
    assert_eq!(tuple.to_sql(), chained.to_sql());
}

#[test]
fn test_runtime_params_use_render_order_regardless_of_build_order() {
    // Regression: runtime `param` placeholders are numbered as they render (WHERE before ORDER BY),
    // so the `Params` shape callers bind against must be render-ordered (the WHERE param, then the
    // ORDER BY param) no matter what order `where_`/`order_by` were called in. Both build orders must
    // therefore share the exact same `Params` shape — pinned here at the type level.
    fn assert_filter_then_order_shape<'conn, 'scope, Q>(_query: &Q)
    where
        Q: SelectAst<'conn, 'scope, TestConnection, Params = HCons<String, HCons<i32, HNil>>>,
    {
    }

    let canonical = TestConnection
        .from::<User>()
        .where_(|user| user.name.equals(param::<UserName>()))
        .order_by(|(user,)| (user.id + param::<UserId>()).asc());
    let reversed = TestConnection
        .from::<User>()
        .order_by(|(user,)| (user.id + param::<UserId>()).asc())
        .where_(|(user,)| user.name.equals(param::<UserName>()));

    assert_filter_then_order_shape(&canonical);
    assert_filter_then_order_shape(&reversed);
}

#[test]
fn test_order_by_tuple_matches_chained_terms() {
    // A tuple of orderings in one call renders identically to chaining `order_by`.
    let tuple = TestConnection
        .from::<User>()
        .order_by(|(user,)| (user.id.asc(), user.name.desc()))
        .select(|(user,)| (user.id, user.name));
    let chained = TestConnection
        .from::<User>()
        .order_by(|(user,)| user.id.asc())
        .order_by(|(user,)| user.name.desc())
        .select(|(user,)| (user.id, user.name));
    assert_eq!(
        tuple.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_0.name AS t1_name \
         FROM public.users AS q0_0 ORDER BY q0_0.id ASC, q0_0.name DESC"
    );
    assert_eq!(tuple.to_sql(), chained.to_sql());
}

#[test]
fn test_having_tuple_predicates_are_anded() {
    // A tuple of HAVING predicates is AND-joined, identically to chaining `having`.
    let q = TestConnection
        .from::<User>()
        .group_by(|(user,)| user.name)
        .having(|(user,)| {
            (
                user.id.count().greater_than(1i64),
                user.id.count().less_than(10i64),
            )
        })
        .select(|(user,)| (user.name, user.id.count()));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.name AS t0_name, COUNT(q0_0.id) AS t1_expr \
         FROM public.users AS q0_0 GROUP BY q0_0.name \
         HAVING (COUNT(q0_0.id) > ?) AND (COUNT(q0_0.id) < ?)"
    );
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Int(1), TestParam::Int(10)]
    );
}

#[test]
fn test_in_subquery_uncorrelated_renders_nested_select() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.id.in_subquery(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(5))
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IN (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (q1_0.user_id = ?)))"
    );
    assert_eq!(q.collect_params().unwrap(), vec![TestParam::Int(5)]);
}

#[test]
fn test_in_subquery_correlated_references_outer_column() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.id.in_subquery(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(user.id))
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IN (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (q1_0.user_id = q0_0.id)))"
    );
    assert_eq!(q.collect_params().unwrap(), Vec::<TestParam>::new());
}

#[test]
fn test_not_in_subquery_renders_not_in() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.id
                .not_in_subquery(sub.from::<Post>().select_subquery(|(post,)| post.user_id))
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id NOT IN (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0))"
    );
}

#[test]
fn test_exists_correlated_subquery_renders() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            exists(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(user.id))
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (EXISTS (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (q1_0.user_id = q0_0.id)))"
    );
}

#[test]
fn test_not_exists_subquery_renders() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(_user,), sub| {
            not_exists(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(1))
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (NOT EXISTS (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (q1_0.user_id = ?)))"
    );
    assert_eq!(q.collect_params().unwrap(), vec![TestParam::Int(1)]);
}

#[test]
fn test_nested_subqueries_reusing_handle_get_distinct_aliases() {
    // Reuse the captured outer handle (`sub`) to build a subquery nested inside another of its
    // subqueries. Each `from` hands out a fresh depth, so the inner table is `q2_0` (not a second
    // `q1_0`), and the correlation references the enclosing subquery's `q1_0` unambiguously.
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(_user,), sub| {
            exists(
                sub.from::<Post>()
                    .where_correlated(|(post,), _inner| {
                        exists(
                            sub.from::<Comment>()
                                .where_(|comment| comment.post_id.equals(post.id))
                                .select_subquery(|(comment,)| comment.post_id),
                        )
                    })
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (EXISTS (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (EXISTS (SELECT \
         q2_0.post_id AS post_id FROM comments AS q2_0 WHERE (q2_0.post_id = q1_0.id)))))"
    );
}

#[test]
fn test_exists_accepts_a_multi_column_subquery_projection() {
    // EXISTS ignores the select-list shape, so a multi-column (tuple) projection is allowed.
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            exists(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(user.id))
                    .select_subquery(|(post,)| (post.id, post.user_id)),
            )
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (EXISTS (SELECT \
         q1_0.id AS t0_id, q1_0.user_id AS t1_user_id FROM posts AS q1_0 WHERE \
         (q1_0.user_id = q0_0.id)))"
    );
}

#[test]
fn test_in_subquery_with_outer_and_inner_params_orders_binds() {
    // Outer filter param, then a subquery containing its own literal: binds must come out in render
    // order (outer WHERE operand has no bind here; the inner literal renders inside the subquery).
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.id.in_subquery(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(7))
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .where_(|(user,)| user.name.equals("ada"))
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IN (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (q1_0.user_id = ?))) AND (q0_0.name = ?)"
    );
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Int(7), TestParam::Text("ada".to_owned())]
    );
}

#[test]
fn test_scalar_subquery_as_comparison_operand() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.id.equals(scalar_subquery(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(user.id))
                    .select_subquery(|(post,)| post.user_id),
            ))
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id = (SELECT \
         q1_0.user_id AS user_id FROM posts AS q1_0 WHERE (q1_0.user_id = q0_0.id)))"
    );
}

#[test]
fn test_scalar_subquery_in_projection() {
    let q = TestConnection
        .from::<User>()
        .select_correlated(|(user,), sub| {
            scalar_subquery(
                sub.from::<Post>()
                    .where_(|post| post.user_id.equals(user.id))
                    .select_subquery(|(post,)| post.id),
            )
        });

    assert_eq!(
        q.to_sql(),
        "SELECT (SELECT q1_0.id AS id FROM posts AS q1_0 WHERE (q1_0.user_id = q0_0.id)) AS expr \
         FROM public.users AS q0_0"
    );
}

#[test]
fn test_in_subquery_against_a_newtype_column() {
    // A `ColumnType` newtype operand matches a subquery projecting the same newtype column. (The
    // value-type guard rejects mixing it with an `i32`-projecting subquery — see the compile-fail
    // test `in_subquery_type_mismatch`.)
    let q = TestConnection
        .from::<Event>()
        .where_correlated(|(event,), sub| {
            event.ledger_ref.in_subquery(
                sub.from::<Event>()
                    .select_subquery(|(other,)| other.ledger_ref),
            )
        })
        .select(|(event,)| event.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM events AS q0_0 WHERE (q0_0.ledger_ref IN (SELECT \
         q1_0.ledger_ref AS ledger_ref FROM events AS q1_0))"
    );
}

#[test]
fn test_in_subquery_against_a_nullable_column_is_allowed() {
    // `x IN (SELECT nullable_col …)` is valid SQL: the column kind's value type is the non-null
    // inner type, so a `String` operand matches a nullable `Option<String>` projected column.
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.name
                .in_subquery(sub.from::<Event>().select_subquery(|(event,)| event.label))
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.name IN (SELECT \
         q1_0.label AS label FROM events AS q1_0))"
    );
}

#[test]
fn test_scalar_subquery_of_a_nullable_column_is_null_testable() {
    // A scalar subquery over a nullable column keeps its nullable kind, so `is_null` is available.
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(_user,), sub| {
            scalar_subquery(
                sub.from::<Event>()
                    .where_(|event| event.ledger_ref.equals(LedgerRef(1)))
                    .select_subquery(|(event,)| event.label),
            )
            .is_null()
        })
        .select(|(user,)| user.id);

    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE ((SELECT q1_0.label AS label \
         FROM events AS q1_0 WHERE (q1_0.ledger_ref = ?)) IS NULL)"
    );
}

#[test]
fn test_window_aggregate_over_partition_and_order() {
    let q = TestConnection.from::<Post>().select(|(post,)| {
        post.user_id
            .sum()
            .over(|w| w.partition_by(post.user_id).order_by(post.id.asc()))
    });
    assert_eq!(
        q.to_sql(),
        "SELECT SUM(q0_0.user_id) OVER (PARTITION BY q0_0.user_id ORDER BY q0_0.id ASC) AS expr \
         FROM posts AS q0_0"
    );
}

#[test]
fn test_window_partition_only_and_order_only() {
    let part = TestConnection
        .from::<Post>()
        .select(|(post,)| post.user_id.sum().over(|w| w.partition_by(post.user_id)));
    assert_eq!(
        part.to_sql(),
        "SELECT SUM(q0_0.user_id) OVER (PARTITION BY q0_0.user_id) AS expr FROM posts AS q0_0"
    );

    let ord = TestConnection
        .from::<Post>()
        .select(|(post,)| post.user_id.sum().over(|w| w.order_by(post.id.desc())));
    assert_eq!(
        ord.to_sql(),
        "SELECT SUM(q0_0.user_id) OVER (ORDER BY q0_0.id DESC) AS expr FROM posts AS q0_0"
    );
}

#[test]
fn test_window_multiple_partition_and_order_terms() {
    let q = TestConnection.from::<Post>().select(|(post,)| {
        post.id.sum().over(|w| {
            w.partition_by(post.user_id)
                .partition_by(post.id)
                .order_by(post.id.asc())
                .order_by(post.user_id.desc())
        })
    });
    assert_eq!(
        q.to_sql(),
        "SELECT SUM(q0_0.id) OVER (PARTITION BY q0_0.user_id, q0_0.id ORDER BY q0_0.id ASC, \
         q0_0.user_id DESC) AS expr FROM posts AS q0_0"
    );
}

#[test]
fn test_window_ranking_functions_render() {
    let row_num = TestConnection.from::<Post>().select(|(post,)| {
        row_number().over(|w| w.partition_by(post.user_id).order_by(post.id.asc()))
    });
    assert_eq!(
        row_num.to_sql(),
        "SELECT ROW_NUMBER() OVER (PARTITION BY q0_0.user_id ORDER BY q0_0.id ASC) AS expr \
         FROM posts AS q0_0"
    );

    let ranked = TestConnection
        .from::<Post>()
        .select(|(post,)| rank().over(|w| w.order_by(post.id.desc())));
    assert_eq!(
        ranked.to_sql(),
        "SELECT RANK() OVER (ORDER BY q0_0.id DESC) AS expr FROM posts AS q0_0"
    );

    let dense = TestConnection
        .from::<Post>()
        .select(|(post,)| dense_rank().over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        dense.to_sql(),
        "SELECT DENSE_RANK() OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );
}

#[test]
fn test_window_ntile_binds_its_argument() {
    let q = TestConnection
        .from::<Post>()
        .select(|(post,)| ntile(4).over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        q.to_sql(),
        "SELECT NTILE(?) OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );
    assert_eq!(q.collect_params().unwrap(), vec![TestParam::Int(4)]);
}

#[test]
fn test_window_lag_and_lead_render_with_offset() {
    let lagged = TestConnection
        .from::<Post>()
        .select(|(post,)| lag(post.user_id, 1).over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        lagged.to_sql(),
        "SELECT LAG(q0_0.user_id, ?) OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );
    assert_eq!(lagged.collect_params().unwrap(), vec![TestParam::Int(1)]);

    let led = TestConnection.from::<Post>().select(|(post,)| {
        lead(post.user_id, 2).over(|w| w.partition_by(post.user_id).order_by(post.id.asc()))
    });
    assert_eq!(
        led.to_sql(),
        "SELECT LEAD(q0_0.user_id, ?) OVER (PARTITION BY q0_0.user_id ORDER BY q0_0.id ASC) AS expr \
         FROM posts AS q0_0"
    );
    assert_eq!(led.collect_params().unwrap(), vec![TestParam::Int(2)]);
}

#[test]
fn test_window_lag_over_left_joined_column_flattens_nullable() {
    // LAG over a left-joined (already-nullable) column must flatten to a single `Option<T>`, not
    // `Option<Option<T>>`. This compiles only because the result row type is `Option<i32>`.
    let q = TestConnection
        .from::<User>()
        .left_join::<Post>()
        .on(|(user,), post| post.user_id.equals(user.id))
        .select(|(user, post)| lag(post.user_id, 1).over(|w| w.order_by(user.id.asc())));
    assert_eq!(
        q.to_sql(),
        "SELECT LAG(q0_1.user_id, ?) OVER (ORDER BY q0_0.id ASC) AS expr FROM public.users AS q0_0 \
         LEFT JOIN posts AS q0_1 ON (q0_1.user_id = q0_0.id)"
    );

    // Pin the decoded row type to `Option<i32>` (a regression to `Option<Option<i32>>` would fail
    // this bound).
    fn assert_row_option_i32<'b, 's, Base, Projection, Q>(_q: &Q)
    where
        Q: SelectQuery<'b, 's, Base, Projection, Row = Option<i32>>,
        Base: SelectAst<'b, 's, Q::Builder>,
        Projection: Projectable,
    {
    }
    assert_row_option_i32(&q);
}

#[test]
fn test_window_lag_over_a_derived_expression() {
    // LAG over a derived scalar expression (`post.id + 1`) compiles and renders.
    let q = TestConnection
        .from::<Post>()
        .select(|(post,)| lag(post.id + 1, 1).over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        q.to_sql(),
        "SELECT LAG((q0_0.id + ?), ?) OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Int(1), TestParam::Int(1)]
    );
}

#[test]
fn test_window_lag_lead_over_arithmetic_expression_kinds() {
    // Exercise the non-`Add` arithmetic operand kinds (Subtract/Multiply/Divide) through LAG/LEAD,
    // confirming their `IntoWindowNullable` impls accept derived-expression operands.
    let subtract = TestConnection
        .from::<Post>()
        .select(|(post,)| lag(post.id - 1, 1).over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        subtract.to_sql(),
        "SELECT LAG((q0_0.id - ?), ?) OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );

    let multiply = TestConnection
        .from::<Post>()
        .select(|(post,)| lead(post.id * 2, 1).over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        multiply.to_sql(),
        "SELECT LEAD((q0_0.id * ?), ?) OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );

    let divide = TestConnection
        .from::<Post>()
        .select(|(post,)| lag(post.id / 2, 1).over(|w| w.order_by(post.id.asc())));
    assert_eq!(
        divide.to_sql(),
        "SELECT LAG((q0_0.id / ?), ?) OVER (ORDER BY q0_0.id ASC) AS expr FROM posts AS q0_0"
    );
}

#[test]
fn test_distinct_single_column() {
    let q = TestConnection
        .from::<User>()
        .distinct()
        .select(|(user,)| user.name);
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.name AS name FROM public.users AS q0_0"
    );
}

#[test]
fn test_distinct_tuple_projection() {
    let q = TestConnection
        .from::<User>()
        .distinct()
        .select(|(user,)| (user.id, user.name));
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.id AS t0_id, q0_0.name AS t1_name FROM public.users AS q0_0"
    );
}

#[test]
fn test_distinct_composes_with_where_order_limit() {
    // `distinct()` works regardless of chain position (here before order_by/limit) and the rendered
    // DISTINCT still lands directly after SELECT.
    let q = TestConnection
        .from::<User>()
        .where_(|user| user.id.greater_than(0))
        .distinct()
        .order_by(|(user,)| user.name.asc())
        .limit(10)
        .select(|(user,)| user.name);
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.name AS name FROM public.users AS q0_0 \
         WHERE (q0_0.id > ?) ORDER BY q0_0.name ASC LIMIT 10"
    );
    assert_eq!(q.collect_params().unwrap(), vec![TestParam::Int(0)]);
}

#[test]
fn test_distinct_order_by_selected_reverse_chain_order() {
    // The DISTINCT + ORDER BY guard is independent of chain order: here `order_by` precedes `distinct`,
    // and the ordering key (`name`) is in the projection, so it compiles and renders.
    let q = TestConnection
        .from::<User>()
        .order_by(|(user,)| user.name.asc())
        .distinct()
        .select(|(user,)| user.name);
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.name AS name FROM public.users AS q0_0 ORDER BY q0_0.name ASC"
    );
}

#[test]
fn test_distinct_multi_key_order_all_selected() {
    // Every ORDER BY key (`id`, `name`) appears in the projection, so the multi-key distinct ordering
    // is accepted.
    let q = TestConnection
        .from::<User>()
        .distinct()
        .order_by(|(user,)| (user.id.asc(), user.name.desc()))
        .select(|(user,)| (user.id, user.name));
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.id AS t0_id, q0_0.name AS t1_name FROM public.users AS q0_0 \
         ORDER BY q0_0.id ASC, q0_0.name DESC"
    );
}

#[test]
fn test_distinct_whole_row_select_no_order() {
    // A whole-row projection's shape is not a single `ExprKind`/tuple; the guard must still accept a
    // distinct query with no ordering over it.
    let q = TestConnection.from::<User>().distinct().select(|(u,)| u);
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.id AS id, q0_0.name AS name FROM public.users AS q0_0"
    );
}

#[test]
fn test_distinct_order_by_column_with_whole_row_select() {
    // Ordering by a column whose whole-row projection includes it is accepted (the row shape expands to
    // its column kinds for the membership check).
    let q = TestConnection
        .from::<User>()
        .distinct()
        .order_by(|(u,)| u.id.asc())
        .select(|(u,)| u);
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.id AS id, q0_0.name AS name FROM public.users AS q0_0 ORDER BY q0_0.id ASC"
    );
}

#[test]
fn test_distinct_order_key_captured_before_right_join_is_nullable_normalized() {
    // `order_by` runs before a RIGHT JOIN, so the key is the bare `UserId` while the projection's base
    // column is nullable-wrapped (`Nullable<UserId>`); the guard matches a key against a projected
    // `Nullable<key>`.
    let q = TestConnection
        .from::<User>()
        .order_by(|(u,)| u.id.asc())
        .right_join::<Post>()
        .on(|(user,), post| post.user_id.equals(user.id))
        .distinct()
        .select(|(user, _post)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT DISTINCT q0_0.id AS id FROM public.users AS q0_0 \
         RIGHT JOIN posts AS q0_1 ON (q0_1.user_id = q0_0.id) ORDER BY q0_0.id ASC"
    );
}

#[test]
fn test_count_distinct_renders_distinct_inside_call() {
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.count().distinct());
    assert_eq!(
        q.to_sql(),
        "SELECT COUNT(DISTINCT q0_0.id) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_sum_distinct_renders_distinct_inside_call() {
    // `.distinct()` generalizes across aggregates (test backend omits the SUM cast the real backends
    // emit).
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.sum().distinct());
    assert_eq!(
        q.to_sql(),
        "SELECT SUM(DISTINCT q0_0.id) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_count_without_distinct_unchanged() {
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| user.id.count());
    assert_eq!(
        q.to_sql(),
        "SELECT COUNT(q0_0.id) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_distinct_inside_subquery() {
    let q = TestConnection
        .from::<User>()
        .where_correlated(|(user,), sub| {
            user.id.in_subquery(
                sub.from::<Post>()
                    .distinct()
                    .select_subquery(|(post,)| post.user_id),
            )
        })
        .select(|(user,)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 WHERE (q0_0.id IN (SELECT DISTINCT \
         q1_0.user_id AS user_id FROM posts AS q1_0))"
    );
}

// Pin a query's decoded row type at compile time (a nullability regression fails the bound).
fn assert_row<'b, 's, Base, Projection, Q, R>(_q: &Q)
where
    Q: SelectQuery<'b, 's, Base, Projection, Row = R>,
    Base: SelectAst<'b, 's, Q::Builder>,
    Projection: Projectable,
{
}

#[test]
fn test_right_join_makes_base_nullable() {
    // RIGHT JOIN: the joined table (Post) stays non-null; the accumulated base (User) becomes nullable.
    let q = TestConnection
        .from::<User>()
        .right_join::<Post>()
        .on(|(user,), post| post.user_id.equals(user.id))
        .select(|(user, post)| (user.id, post.id));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_1.id AS t1_id FROM public.users AS q0_0 \
         RIGHT JOIN posts AS q0_1 ON (q0_1.user_id = q0_0.id)"
    );
    // Base `user.id` decodes `Option<i32>`; joined `post.id` stays `i32`.
    assert_row::<_, _, _, (Option<i32>, i32)>(&q);
}

// (FULL JOIN is gated to `SupportsFullJoin` backends, which `TestBackend` is not — see the
// `full_join_rejected_without_capability` compile-fail case. Full-join rendering/nullability is
// covered by the PostgreSQL backend tests.)

#[test]
fn test_right_join_flattens_already_nullable_base_column() {
    // A base column already declared `Option<T>` (`Event::label`) must stay a single `Option<T>` after
    // the right-join nullable-wrap, not become `Option<Option<T>>`. This holds because a column kind's
    // `Value` is the inner non-null type, so `Nullable<K>` adds exactly one `Option` layer.
    let q = TestConnection
        .from::<Event>()
        .right_join::<Post>()
        .on(|(event,), post| post.id.equals(event.id))
        .select(|(event, post)| (event.label, post.id));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.label AS t0_label, q0_1.id AS t1_id FROM events AS q0_0 \
         RIGHT JOIN posts AS q0_1 ON (q0_1.id = q0_0.id)"
    );
    // `event.label` decodes `Option<String>` (one layer), `post.id` stays `i32`.
    assert_row::<_, _, _, (Option<String>, i32)>(&q);
}

#[test]
fn test_right_join_then_inner_join_keeps_earlier_base_nullable() {
    // A later inner join does not un-nullable the already-right-joined base; the new table is non-null.
    let q = TestConnection
        .from::<User>()
        .right_join::<Post>()
        .on(|(user,), post| post.user_id.equals(user.id))
        .join::<Comment>()
        .on(|(_user, post), comment| comment.post_id.equals(post.id))
        .select(|(user, post, comment)| (user.id, post.id, comment.id));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_1.id AS t1_id, q0_2.id AS t2_id FROM public.users AS q0_0 \
         RIGHT JOIN posts AS q0_1 ON (q0_1.user_id = q0_0.id) \
         INNER JOIN comments AS q0_2 ON (q0_2.post_id = q0_1.id)"
    );
    assert_row::<_, _, _, (Option<i32>, i32, i32)>(&q);
}

#[test]
fn test_bytea_vec_u8_column_binds_in_queries() {
    // Regression for ed37021: a `Vec<u8>` (bytea) column must compile in insert/where/select and a
    // nullable `Option<Vec<u8>>` column too. Before the fix, `Vec<u8>: ColumnNullability/ExprKind`
    // were unsatisfied and these builders failed to compile.
    let insert = TestConnection
        .to::<Blob>()
        .data(vec![0xDE, 0xAD, 0xBE, 0xEF])
        .maybe(Some(vec![0x01, 0x02]))
        .insert_returning(|blob| blob.id);
    assert_eq!(
        insert.to_sql(),
        "INSERT INTO blobs (data, maybe) VALUES (?, ?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        insert.collect_params().unwrap(),
        vec![
            TestParam::Bytes(vec![0xDE, 0xAD, 0xBE, 0xEF]),
            TestParam::Bytes(vec![0x01, 0x02]),
        ]
    );

    // A NULL for the nullable column.
    let insert_null = TestConnection
        .to::<Blob>()
        .data(vec![0x00])
        .maybe(None)
        .insert_returning(|blob| blob.id);
    assert_eq!(
        insert_null.collect_params().unwrap(),
        vec![TestParam::Bytes(vec![0x00]), TestParam::Null]
    );

    // Predicate operand + projection of both the non-null and nullable byte columns.
    let q = TestConnection
        .from::<Blob>()
        .where_(|b| b.data.equals(vec![1u8, 2, 3]))
        .select(|(b,)| (b.data, b.maybe));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.data AS t0_data, q0_0.maybe AS t1_maybe FROM blobs AS q0_0 WHERE (q0_0.data = ?)"
    );
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Bytes(vec![1, 2, 3])]
    );
    // `data` decodes `Vec<u8>`, the nullable column decodes `Option<Vec<u8>>`.
    assert_row::<_, _, _, (Vec<u8>, Option<Vec<u8>>)>(&q);
}

#[test]
fn test_fixed_bytes_column_binds_in_queries() {
    // Coverage for d10dcc0 on the test backend: a `[u8; N]` column (and `Option<[u8; N]>`) must work
    // in insert/where/select and bind as bytes, like `Vec<u8>`.
    let insert = TestConnection
        .to::<FixedBlob>()
        .key([0xDE, 0xAD, 0xBE, 0xEF])
        .nonce(Some([0x01, 0x02]))
        .insert_returning(|blob| blob.id);
    assert_eq!(
        insert.collect_params().unwrap(),
        vec![
            TestParam::Bytes(vec![0xDE, 0xAD, 0xBE, 0xEF]),
            TestParam::Bytes(vec![0x01, 0x02]),
        ]
    );

    let null_nonce = TestConnection
        .to::<FixedBlob>()
        .key([0, 0, 0, 0])
        .nonce(None)
        .insert_returning(|blob| blob.id);
    assert_eq!(
        null_nonce.collect_params().unwrap(),
        vec![TestParam::Bytes(vec![0, 0, 0, 0]), TestParam::Null]
    );

    let q = TestConnection
        .from::<FixedBlob>()
        .where_(|b| b.key.equals([1u8, 2, 3, 4]))
        .select(|(b,)| (b.key, b.nonce));
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Bytes(vec![1, 2, 3, 4])]
    );
    // `key` decodes `[u8; 4]`, the nullable column decodes `Option<[u8; 2]>`.
    assert_row::<_, _, _, ([u8; 4], Option<[u8; 2]>)>(&q);
}

#[test]
fn test_bytea_borrowed_setters_and_operands() {
    // `&[u8]` / `&Vec<u8>` work as setters and predicate operands (mirroring `&str`/`&String`),
    // skipping a caller-side clone.
    let owned = vec![0xCAu8, 0xFE];
    let insert = TestConnection
        .to::<Blob>()
        .data(&owned[..]) // &[u8]
        .maybe(Some(owned.clone()))
        .insert_returning(|blob| blob.id);
    assert_eq!(
        insert.collect_params().unwrap(),
        vec![
            TestParam::Bytes(vec![0xCA, 0xFE]),
            TestParam::Bytes(vec![0xCA, 0xFE]),
        ]
    );

    let q = TestConnection
        .from::<Blob>()
        .where_(|b| b.data.equals(&owned)) // &Vec<u8>
        .select(|(b,)| b.id);
    assert_eq!(
        q.collect_params().unwrap(),
        vec![TestParam::Bytes(vec![0xCA, 0xFE])]
    );

    // Nullable setter: borrowed `&[u8]` and a bare owned `Vec<u8>` (not just `Some(..)`/`None`).
    let nullable_borrowed = TestConnection
        .to::<Blob>()
        .data(vec![0x00])
        .maybe(&owned[..])
        .insert_returning(|blob| blob.id);
    assert_eq!(
        nullable_borrowed.collect_params().unwrap(),
        vec![
            TestParam::Bytes(vec![0x00]),
            TestParam::Bytes(vec![0xCA, 0xFE])
        ]
    );
    let nullable_owned_bare = TestConnection
        .to::<Blob>()
        .data(vec![0x00])
        .maybe(vec![0x09]) // bare owned Vec<u8> on a nullable column
        .insert_returning(|blob| blob.id);
    assert_eq!(
        nullable_owned_bare.collect_params().unwrap(),
        vec![TestParam::Bytes(vec![0x00]), TestParam::Bytes(vec![0x09])]
    );

    // Explicit multi-column row insert with borrowed bytes (non-null + nullable columns).
    let explicit = TestConnection
        .to_columns::<Blob, (BlobData, BlobMaybe)>()
        .row((&owned[..], &owned[..]))
        .insert_returning(|blob| blob.id);
    assert_eq!(
        explicit.collect_params().unwrap(),
        vec![
            TestParam::Bytes(vec![0xCA, 0xFE]),
            TestParam::Bytes(vec![0xCA, 0xFE]),
        ]
    );
}

#[test]
fn test_case_with_else_renders_and_binds_in_order() {
    let q = TestConnection.from::<User>().select(|(user,)| {
        case()
            .when(user.id.greater_than(10), 1)
            .when(user.id.greater_than(5), 2)
            .otherwise(0)
    });
    assert_eq!(
        q.to_sql(),
        "SELECT CASE WHEN (q0_0.id > ?) THEN ? WHEN (q0_0.id > ?) THEN ? ELSE ? END AS expr \
         FROM public.users AS q0_0"
    );
    // Binds in render order: pred, then, pred, then, else.
    assert_eq!(
        q.collect_params().unwrap(),
        vec![
            TestParam::Int(10),
            TestParam::Int(1),
            TestParam::Int(5),
            TestParam::Int(2),
            TestParam::Int(0),
        ]
    );
    assert_row::<_, _, _, i32>(&q);
}

#[test]
fn test_case_without_else_is_nullable() {
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| case().when(user.id.greater_than(5), 1).end());
    assert_eq!(
        q.to_sql(),
        "SELECT CASE WHEN (q0_0.id > ?) THEN ? END AS expr FROM public.users AS q0_0"
    );
    // No ELSE -> Option<i32>.
    assert_row::<_, _, _, Option<i32>>(&q);
}

#[test]
fn test_case_usable_in_where() {
    // A non-aggregate CASE is a valid WHERE operand.
    let q = TestConnection
        .from::<User>()
        .where_(|user| {
            case()
                .when(user.id.greater_than(5), 1)
                .otherwise(0)
                .equals(1)
        })
        .select(|(user,)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 \
         WHERE (CASE WHEN (q0_0.id > ?) THEN ? ELSE ? END = ?)"
    );
    assert_eq!(
        q.collect_params().unwrap(),
        vec![
            TestParam::Int(5),
            TestParam::Int(1),
            TestParam::Int(0),
            TestParam::Int(1),
        ]
    );
}

// (A CASE whose WHEN references a bare column *and* whose THEN is an aggregate is rejected — like
// `COUNT(id) + id`, a column and an aggregate cannot mix in one expression. Aggregate *conditions*
// with non-column comparisons are fine; see `test_case_with_aggregate_condition_is_aggregate`.)

#[test]
fn test_case_with_aggregate_condition_is_aggregate() {
    // An aggregate inside a WHEN *condition* makes the whole CASE an aggregate projection — valid in a
    // whole-table aggregate select even though every THEN/ELSE value is a constant.
    let q = TestConnection.from::<User>().select(|(user,)| {
        case()
            .when(user.id.count().greater_than(1i64), 1i64)
            .otherwise(0i64)
    });
    assert_eq!(
        q.to_sql(),
        "SELECT CASE WHEN (COUNT(q0_0.id) > ?) THEN ? ELSE ? END AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_case_with_subquery_condition_classifies() {
    // A CASE arm condition may be a subquery predicate (exists / in_subquery); the CASE still
    // classifies as a projection (scalar here).
    let q = TestConnection
        .from::<User>()
        .select_correlated(|(user,), sub| {
            case()
                .when(
                    exists(
                        sub.from::<Post>()
                            .where_(|post| post.user_id.equals(user.id))
                            .select_subquery(|(post,)| post.user_id),
                    ),
                    1,
                )
                .otherwise(0)
        });
    let sql = q.to_sql();
    assert!(
        sql.contains("CASE WHEN (EXISTS (SELECT") && sql.contains("END AS expr"),
        "{sql}"
    );
}

#[test]
fn test_case_with_nullable_branch_is_nullable() {
    // `event.label` is a nullable column, so a CASE with it as a branch is nullable *even with an
    // ELSE* — its result decodes as `Option<String>`. `is_null` (only available on nullable
    // expressions) is therefore callable on the result; a non-null-branch CASE rejects it (see the
    // `case_nonnull_branches_are_not_nullable` compile-fail test).
    let q = TestConnection
        .from::<Event>()
        .where_(|event| {
            case()
                .when(event.id.greater_than(0), event.label)
                .otherwise("default".to_string())
                .is_null()
        })
        .select(|(event,)| event.id);
    let sql = q.to_sql();
    assert!(sql.contains("IS NULL"), "{sql}");
}

#[test]
fn test_case_with_columntype_newtype_branches() {
    // A `#[derive(ColumnType)]` newtype value is a non-null value type usable as a CASE branch, and a
    // newtype CASE result is projectable as a standalone scalar (it decodes back to the newtype).
    let q = TestConnection.from::<Event>().select(|(event,)| {
        case()
            .when(event.id.greater_than(0), LedgerRef(1))
            .otherwise(LedgerRef(0))
    });
    let sql = q.to_sql();
    assert!(
        sql.contains("CASE WHEN") && sql.contains("END AS expr"),
        "{sql}"
    );
}

#[test]
fn test_case_with_sum_aggregate_branch_is_nullable() {
    // A SUM/AVG/MIN/MAX aggregate has an `Option<_>` value type; as a CASE branch its value type is
    // the inner type and the result is nullable, so the CASE finishes (regression: it used to set
    // `T = Option<_>` and fail to finish). The COUNT condition keeps the whole CASE an aggregate (a
    // bare-column condition + aggregate value would be rejected, like `COUNT(id) + id`).
    let q = TestConnection.from::<Counter>().select(|(counter,)| {
        case()
            .when(
                counter.count.count().greater_than(0i64),
                counter.count.sum(),
            )
            .end()
    });
    let sql = q.to_sql();
    assert!(
        sql.contains("CASE WHEN") && sql.contains("SUM(") && sql.contains("END AS expr"),
        "{sql}"
    );
}

#[test]
fn test_case_with_outer_join_column_branch_is_nullable() {
    // A left-joined column is `Nullable<K>` (value type `Option<_>`); as a CASE branch its value type
    // is the inner type and the result is nullable, so the CASE both finishes and `is_null`s.
    let q = TestConnection
        .from::<User>()
        .left_join::<Post>()
        .on(|(user,), post| post.user_id.equals(user.id))
        .where_(|(user, post)| {
            case()
                .when(user.id.greater_than(0), post.user_id)
                .otherwise(0)
                .is_null()
        })
        .select(|(user, _post)| user.id);
    let sql = q.to_sql();
    assert!(
        sql.contains("CASE WHEN") && sql.contains("IS NULL"),
        "{sql}"
    );
}

// A nullable column declared through a type alias: nullability is only visible at the type level via
// `ColumnNullability`, not a syntactic `Option<…>` token.
type MaybeLabel = Option<String>;

#[derive(Clone, Debug, PartialEq, Table)]
struct Aliased<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    label: C::Type<'scope, MaybeLabel>,
}

#[test]
fn test_case_with_type_aliased_nullable_branch_is_nullable() {
    // The column kind's CASE nullability must come from the alias-transparent ColumnNullability path,
    // so an aliased Option column branch makes the CASE nullable (is_null callable).
    let q = TestConnection
        .from::<Aliased>()
        .where_(|row| {
            case()
                .when(row.id.greater_than(0), row.label)
                .otherwise("x".to_string())
                .is_null()
        })
        .select(|(row,)| row.id);
    let sql = q.to_sql();
    assert!(sql.contains("IS NULL"), "{sql}");
}

#[derive(Clone, Debug, PartialEq, Table)]
struct AliasedRequired<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    name: C::Type<'scope, String>,
    label: C::Type<'scope, MaybeLabel>,
}

#[test]
fn test_insert_select_omits_alias_nullable_column() {
    // `label` is nullable through a type alias, so it is omittable from an `INSERT … SELECT` target
    // list — the required-column coverage resolves nullability type-level via `ColumnNullability`, not a
    // syntactic `Option<…>` check. This must compile (only the required, non-null `name` is covered).
    let conn = TestConnection;
    let query = conn.to::<AliasedRequired>().insert_select(
        |aliased| aliased.name,
        conn.from::<AliasedRequired>()
            .select(|(aliased,)| aliased.name),
    );
    let sql = query.to_sql();
    assert!(sql.contains("INSERT INTO") && sql.contains("name"), "{sql}");
}

#[test]
fn test_case_with_in_subquery_condition_classifies() {
    // A non-aggregate `in_subquery` condition (column operand) keeps the CASE a scalar projection.
    let q = TestConnection
        .from::<User>()
        .select_correlated(|(user,), sub| {
            case()
                .when(
                    user.id
                        .in_subquery(sub.from::<Post>().select_subquery(|(post,)| post.user_id)),
                    1,
                )
                .otherwise(0)
        });
    let sql = q.to_sql();
    assert!(
        sql.contains("CASE WHEN (q0_0.id IN (SELECT") && sql.contains("END AS expr"),
        "{sql}"
    );
}

#[test]
fn test_case_in_returning_clause() {
    // A window-free CASE is valid in a RETURNING projection (it implements NonWindowAst).
    let insert = TestConnection
        .to::<User>()
        .name("Ada")
        .insert_returning(|user| case().when(user.id.greater_than(0), 1).otherwise(0));
    let sql = insert.to_sql();
    assert!(
        sql.contains("RETURNING CASE WHEN") && sql.contains("END AS expr"),
        "{sql}"
    );
}

#[test]
fn test_nullif_renders() {
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| nullif(user.id, 0));
    assert_eq!(
        q.to_sql(),
        "SELECT NULLIF(q0_0.id, ?) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_nullif_result_is_nullable() {
    // NULLIF can return NULL (when the operands are equal), so its result is nullable — `is_null`
    // (only on nullable expressions) is callable.
    let q = TestConnection
        .from::<User>()
        .where_(|user| nullif(user.id, 0).is_null())
        .select(|(user,)| user.id);
    assert!(
        q.to_sql().contains("NULLIF(q0_0.id, ?) IS NULL"),
        "{}",
        q.to_sql()
    );
}

#[test]
fn test_coalesce_renders() {
    let q = TestConnection
        .from::<User>()
        .select(|(user,)| coalesce(user.id).or_else(0).end());
    assert_eq!(
        q.to_sql(),
        "SELECT COALESCE(q0_0.id, ?) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_coalesce_all_nullable_is_nullable() {
    // Every argument is nullable (the `label` column), so COALESCE can return NULL -> nullable result
    // (`is_null` callable).
    let q = TestConnection
        .from::<Event>()
        .where_(|event| coalesce(event.label).or_else(event.label).end().is_null())
        .select(|(event,)| event.id);
    assert!(
        q.to_sql()
            .contains("COALESCE(q0_0.label, q0_0.label) IS NULL"),
        "{}",
        q.to_sql()
    );
}

#[test]
fn test_coalesce_collapses_to_non_null() {
    // A non-null fallback collapses the result to non-null (a nullable `label` + a non-null literal):
    // the result is projectable as a non-null `String` (see the compile-fail test
    // `coalesce_non_null_fallback_is_not_nullable` for the `is_null`-rejected guard).
    let q = TestConnection
        .from::<Event>()
        .select(|(event,)| coalesce(event.label).or_else("default").end());
    assert_eq!(
        q.to_sql(),
        "SELECT COALESCE(q0_0.label, ?) AS expr FROM events AS q0_0"
    );
}

#[test]
fn test_simple_case_renders() {
    let q = TestConnection.from::<User>().select(|(user,)| {
        case_of(user.id)
            .when(1, "one")
            .when(2, "two")
            .otherwise("other")
    });
    assert_eq!(
        q.to_sql(),
        "SELECT CASE q0_0.id WHEN ? THEN ? WHEN ? THEN ? ELSE ? END AS expr \
         FROM public.users AS q0_0"
    );
}

#[test]
fn test_simple_case_without_else_is_nullable() {
    // No ELSE: an unmatched operand yields NULL, so the result is nullable (`is_null` callable).
    let q = TestConnection
        .from::<User>()
        .where_(|user| case_of(user.id).when(1, "one").end().is_null())
        .select(|(user,)| user.id);
    assert!(
        q.to_sql()
            .contains("CASE q0_0.id WHEN ? THEN ? END IS NULL"),
        "{}",
        q.to_sql()
    );
}

#[test]
fn test_simple_case_with_nullable_branch_is_nullable() {
    // A nullable THEN value (the `label` column) makes the simple CASE nullable even with an ELSE.
    let q = TestConnection
        .from::<Event>()
        .where_(|event| {
            case_of(event.id)
                .when(1, event.label)
                .otherwise("x".to_string())
                .is_null()
        })
        .select(|(event,)| event.id);
    assert!(q.to_sql().contains("IS NULL"), "{}", q.to_sql());
}

#[test]
fn test_string_functions_render() {
    let lower_q = TestConnection
        .from::<User>()
        .select(|(user,)| lower(user.name));
    assert_eq!(
        lower_q.to_sql(),
        "SELECT LOWER(q0_0.name) AS expr FROM public.users AS q0_0"
    );

    let length_q = TestConnection
        .from::<User>()
        .select(|(user,)| length(user.name));
    assert_eq!(
        length_q.to_sql(),
        "SELECT CHAR_LENGTH(q0_0.name) AS expr FROM public.users AS q0_0"
    );

    // concat chains to nested CONCAT.
    let concat_q = TestConnection
        .from::<User>()
        .select(|(user,)| user.name.concat(" ").concat(user.name));
    assert_eq!(
        concat_q.to_sql(),
        "SELECT CONCAT(CONCAT(q0_0.name, ?), q0_0.name) AS expr FROM public.users AS q0_0"
    );

    let substring_q = TestConnection
        .from::<User>()
        .select(|(user,)| substring(user.name, 1, 3));
    assert_eq!(
        substring_q.to_sql(),
        "SELECT SUBSTRING(q0_0.name FROM ? FOR ?) AS expr FROM public.users AS q0_0"
    );
}

#[test]
fn test_string_function_of_nullable_column_is_nullable() {
    // `event.label` is nullable, so `lower(label)` is nullable — `is_null` (only on nullable
    // expressions) is callable on it. (A non-null operand rejects it — see the compile-fail test
    // `string_fn_result_non_null_when_operand_non_null`.)
    let q = TestConnection
        .from::<Event>()
        .where_(|event| lower(event.label).is_null())
        .select(|(event,)| event.id);
    assert!(
        q.to_sql().contains("LOWER(q0_0.label) IS NULL"),
        "{}",
        q.to_sql()
    );
}

#[test]
fn test_string_function_in_returning() {
    // A string function is window-free, so it is valid in a RETURNING projection.
    let insert = TestConnection
        .to::<User>()
        .name("Ada")
        .insert_returning(|user| upper(user.name));
    assert!(
        insert
            .to_sql()
            .contains("RETURNING UPPER(q0_0.name) AS expr"),
        "{}",
        insert.to_sql()
    );
}

// ===== date/time functions (feature-gated on the timestamp type) =====

#[cfg(feature = "systemtime")]
#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct TimedEvent<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment)]
    id: C::Type<'scope, i32>,
    created: C::Type<'scope, std::time::SystemTime>,
    ended: C::Type<'scope, Option<std::time::SystemTime>>,
}

// The in-memory backend can neither bind nor decode a `SystemTime`, so it covers only `extract`
// (which returns `i64`) over timestamp columns — no projecting/binding of bare timestamps. `now()`,
// `date_trunc`, and RETURNING are covered on the PostgreSQL backend.
#[cfg(feature = "systemtime")]
#[test]
fn test_extract_renders() {
    // `extract` renders bare in the test backend (the dialect result cast is dropped, like aggregates).
    let extract_q = TestConnection
        .from::<TimedEvent>()
        .select(|(e,)| extract(DateField::Year, e.created));
    assert_eq!(
        extract_q.to_sql(),
        "SELECT EXTRACT(YEAR FROM q0_0.created) AS expr FROM public.timed_events AS q0_0"
    );
}

#[cfg(feature = "systemtime")]
#[test]
fn test_extract_of_nullable_column_is_nullable() {
    // `ended` is nullable, so `extract(... ended)` is nullable — `is_null` (only on nullable
    // expressions) is callable on it.
    let q = TestConnection
        .from::<TimedEvent>()
        .where_(|e| extract(DateField::Hour, e.ended).is_null())
        .select(|(e,)| e.id);
    assert!(
        q.to_sql().contains("EXTRACT(HOUR FROM q0_0.ended) IS NULL"),
        "{}",
        q.to_sql()
    );
}

#[cfg(feature = "systemtime")]
#[test]
fn test_extract_second_renders() {
    // `extract(Second)` floors to the whole-seconds component (i64).
    let whole = TestConnection
        .from::<TimedEvent>()
        .select(|(e,)| extract(DateField::Second, e.created));
    assert_eq!(
        whole.to_sql(),
        "SELECT FLOOR(EXTRACT(SECOND FROM q0_0.created)) AS expr FROM public.timed_events AS q0_0"
    );

    // `extract_second` returns fractional seconds (f64); the MySQL-like test backend uses the
    // composite `SECOND_MICROSECOND` unit.
    let frac = TestConnection
        .from::<TimedEvent>()
        .select(|(e,)| extract_second(e.created));
    assert_eq!(
        frac.to_sql(),
        "SELECT EXTRACT(SECOND_MICROSECOND FROM q0_0.created) / 1000000.0 AS expr \
         FROM public.timed_events AS q0_0"
    );

    // `extract_second` over a nullable column is nullable.
    let nullable = TestConnection
        .from::<TimedEvent>()
        .where_(|e| extract_second(e.ended).is_null())
        .select(|(e,)| e.id);
    assert!(
        nullable
            .to_sql()
            .contains("EXTRACT(SECOND_MICROSECOND FROM q0_0.ended) / 1000000.0 IS NULL"),
        "{}",
        nullable.to_sql()
    );
}

#[test]
fn test_cross_join_renders() {
    // CROSS JOIN: Cartesian product, no ON. Both tables' columns stay non-null.
    let q = TestConnection
        .from::<User>()
        .cross_join::<Post>()
        .select(|(user, post)| (user.id, post.id));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_1.id AS t1_id FROM public.users AS q0_0 CROSS JOIN posts AS q0_1"
    );
    assert!(!q.to_sql().contains(" ON "), "{}", q.to_sql());
    assert_row::<_, _, _, (i32, i32)>(&q);
}

#[test]
fn test_self_join_renders_distinct_aliases() {
    // Self-join: the same table joined to itself gets distinct positional aliases (q0_0, q0_1).
    let q = TestConnection
        .from::<Post>()
        .join::<Post>()
        .on(|(post,), other| post.user_id.equals(other.id))
        .select(|(post, other)| (post.id, other.id));
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS t0_id, q0_1.id AS t1_id FROM posts AS q0_0 \
         INNER JOIN posts AS q0_1 ON (q0_0.user_id = q0_1.id)"
    );
    assert_row::<_, _, _, (i32, i32)>(&q);
}

#[test]
fn test_order_by_nulls_first_and_last_render_natively() {
    let q = TestConnection
        .from::<User>()
        .order_by(|(user,)| (user.name.desc().nulls_last(), user.id.asc().nulls_first()))
        .select(|(user,)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 \
         ORDER BY q0_0.name DESC NULLS LAST, q0_0.id ASC NULLS FIRST"
    );
}

#[test]
fn test_for_update_renders_after_limit() {
    let q = TestConnection
        .from::<User>()
        .order_by(|(user,)| user.id.asc())
        .limit(10)
        .for_update()
        .select(|(user,)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 ORDER BY q0_0.id ASC LIMIT 10 FOR UPDATE"
    );
}

#[test]
fn test_for_share_renders() {
    let q = TestConnection
        .from::<User>()
        .for_share()
        .select(|(user,)| user.id);
    assert_eq!(
        q.to_sql(),
        "SELECT q0_0.id AS id FROM public.users AS q0_0 FOR SHARE"
    );
}

#[test]
fn test_insert_select_renders() {
    // INSERT INTO t (cols) SELECT … — the inserted rows come from a query whose projected row type
    // matches the target columns.
    let conn = TestConnection;
    let q = conn.to::<User>().insert_select(
        |user| user.name,
        conn.from::<User>()
            .where_(|user| user.id.greater_than(10))
            .select(|(user,)| user.name),
    );
    assert_eq!(
        q.to_sql(),
        "INSERT INTO public.users (name) \
         SELECT q0_0.name AS name FROM public.users AS q0_0 WHERE (q0_0.id > ?)"
    );
    assert_eq!(q.collect_params().unwrap(), vec![TestParam::Int(10)]);
}

#[test]
fn test_insert_select_union_source_renders() {
    // A set-op source (`select(...).union(...)`) inserts as `INSERT INTO t (cols) <union>`. The union
    // is the insert source directly — no *outer* parentheses wrap it (the per-arm parens are the normal
    // set-op rendering).
    let conn = TestConnection;
    let q = conn.to::<User>().insert_select(
        |user| user.name,
        conn.from::<User>()
            .select(|(user,)| user.name)
            .union(conn.from::<User>().select(|(user,)| user.name)),
    );
    assert_eq!(
        q.to_sql(),
        "INSERT INTO public.users (name) \
         (SELECT q0_0.name AS name FROM public.users AS q0_0) \
         UNION (SELECT q0_0.name AS name FROM public.users AS q0_0)"
    );
}

#[test]
fn test_insert_select_locked_source_renders() {
    // A single *locked* source (`for_update()`) is a valid insert source — it renders `FOR UPDATE`,
    // locking the copied rows. (The row-lock ban applies only to set-op operands, not single selects.)
    let conn = TestConnection;
    let q = conn.to::<User>().insert_select(
        |user| user.name,
        conn.from::<User>().for_update().select(|(user,)| user.name),
    );
    assert_eq!(
        q.to_sql(),
        "INSERT INTO public.users (name) \
         SELECT q0_0.name AS name FROM public.users AS q0_0 FOR UPDATE"
    );
}
