//! Dialect tests for the in-memory test backend.
//!
//! These pin the test backend's SQL output directly, rather than relying on the
//! incidental assertions in `squealy`'s `derive_metadata.rs`. The notable
//! differences from the PostgreSQL backend are the `?` bind placeholders (vs
//! `$1`, `$2`) and the `AUTOINCREMENT` DDL keyword (vs
//! `GENERATED BY DEFAULT AS IDENTITY`).

use squealy::*;
use squealy_test::{TestBackend, TestConnection};

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct User<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment, db_type = "integer")]
    id: C::Type<'scope, i32>,
    name: C::Type<'scope, String>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct DefaultedRecord<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment, db_type = "integer")]
    id: C::Type<'scope, i32>,
}

#[allow(dead_code)]
#[derive(Schema)]
struct Public {
    users: User<'static, ColumnName>,
}

#[test]
fn test_select_uses_question_mark_placeholders() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.id.equals(1))
        .select(|(user,)| user.id + 2);

    assert_eq!(
        users.to_sql(),
        "SELECT (q0_0.id + ?) AS expr FROM public.users AS q0_0 WHERE (q0_0.id = ?)"
    );
    let mut written = Vec::new();
    users.write_params(&mut written).unwrap();
    assert_eq!(written, vec![BindValue::Int(2), BindValue::Int(1)]);
    assert_eq!(
        users.collect_params(),
        vec![BindValue::Int(2), BindValue::Int(1)]
    );
}

#[test]
fn test_runtime_prepared_params_render_without_captured_values() {
    let users = TestConnection
        .from::<User>()
        .where_(|user| user.name.equals(param::<UserName>()))
        .select(|(user,)| user.name);

    assert_eq!(
        users.to_sql(),
        "SELECT q0_0.name AS name FROM public.users AS q0_0 WHERE (q0_0.name = ?)"
    );
    assert_eq!(users.collect_params(), Vec::<BindValue>::new());
}

#[test]
fn test_runtime_prepared_assignment_params_render_without_captured_values() {
    let insert = TestConnection
        .to::<User>()
        .name(param::<UserName>())
        .insert_returning(|user| user.id);
    let update = TestConnection
        .to::<User>()
        .name(param::<UserName>())
        .where_(|user| user.id.equals(param::<UserId>()))
        .update_returning(|user| user.name);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = ? WHERE (q0_0.id = ?) RETURNING q0_0.name AS name"
    );
    assert_eq!(insert.collect_params(), Vec::<BindValue>::new());
    assert_eq!(update.collect_params(), Vec::<BindValue>::new());
}

#[test]
fn test_insert_update_and_delete_render_returning() {
    let insert = TestConnection
        .to::<User>()
        .name("Ada")
        .insert_returning(|user| user.id);
    let update = TestConnection
        .to::<User>()
        .name("Ada")
        .where_(|user| user.id.equals(1))
        .update_returning(|user| (user.id, user.name));
    let delete = TestConnection
        .from::<User>()
        .where_(|user| user.id.equals(1))
        .delete_returning(|user| user);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = ? WHERE (q0_0.id = ?) RETURNING q0_0.id AS t0_id, q0_0.name AS t1_name"
    );
    assert_eq!(
        delete.to_sql(),
        "DELETE FROM public.users AS q0_0 WHERE (q0_0.id = ?) RETURNING q0_0.id AS id, q0_0.name AS name"
    );
    assert_eq!(
        insert.collect_params(),
        vec![BindValue::Text("Ada".to_owned())]
    );
    assert_eq!(
        update.collect_params(),
        vec![BindValue::Text("Ada".to_owned()), BindValue::Int(1)]
    );
    assert_eq!(delete.collect_params(), vec![BindValue::Int(1)]);
}

#[test]
fn test_insert_can_use_default_values() {
    let insert = TestConnection
        .to::<DefaultedRecord>()
        .insert_returning(|record| record.id);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO defaulted_records DEFAULT VALUES RETURNING q0_0.id AS id"
    );
    assert_eq!(insert.collect_params(), Vec::<BindValue>::new());
}

#[test]
fn test_queries_can_be_prepared() {
    {
        let select = TestConnection
            .from::<User>()
            .where_(|user| user.id.equals(1))
            .select(|(user,)| user.name);
        let _prepare = select.prepare();
    }

    {
        let insert = TestConnection
            .to::<User>()
            .name("Ada")
            .insert_returning(|user| user.id);
        let _prepare = insert.prepare();
    }

    {
        let update = TestConnection
            .to::<User>()
            .name("Ada")
            .where_(|user| user.id.equals(1))
            .update_returning(|user| user.id);
        let _prepare = update.prepare();
    }

    {
        let delete = TestConnection
            .from::<User>()
            .where_(|user| user.id.equals(1))
            .delete_returning(|user| user.id);
        let _prepare = delete.prepare();
    }
}

#[test]
fn test_runtime_param_queries_can_be_prepared() {
    {
        let select = TestConnection
            .from::<User>()
            .where_(|user| user.name.equals(param::<UserName>()))
            .select(|(user,)| user.id);
        let _prepare = select.prepare();
    }

    {
        let insert = TestConnection
            .to::<User>()
            .name(param::<UserName>())
            .insert_returning(|user| user.id);
        let _prepare = insert.prepare();
    }

    {
        let update = TestConnection
            .to::<User>()
            .name(param::<UserName>())
            .where_(|user| user.id.equals(param::<UserId>()))
            .update_returning(|user| user.id);
        let _prepare = update.prepare();
    }

    {
        let delete = TestConnection
            .from::<User>()
            .where_(|user| user.id.equals(param::<UserId>()))
            .delete_returning(|user| user.id);
        let _prepare = delete.prepare();
    }
}

#[test]
fn test_backend_writes_table_ddl_with_autoincrement() {
    let mut sql = Vec::new();
    let tables = <Public as Schema>::tables().collect::<Vec<_>>();
    TestBackend.write_table(tables[0], &mut sql).unwrap();
    let sql = String::from_utf8(sql).unwrap();

    assert_eq!(
        sql,
        "CREATE TABLE public.users (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL)"
    );
}
