//! Dialect tests for the in-memory test backend.
//!
//! These pin the test backend's SQL output directly, rather than relying on the
//! incidental assertions in `squealy`'s `derive_metadata.rs`. The notable
//! differences from the PostgreSQL backend are the `?` bind placeholders (vs
//! `$1`, `$2`) and the `AUTOINCREMENT` DDL keyword (vs
//! `GENERATED BY DEFAULT AS IDENTITY`).

use squealy::*;
use squealy_test::TestConnection;

#[derive(Clone, Debug, PartialEq, Table)]
#[schema(Public)]
struct User<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment, db_type = "integer")]
    id: C::Type<'scope, i32>,
    name: C::Type<'scope, String>,
}

#[derive(Clone, Debug, PartialEq, Table)]
struct DefaultedRecord<'scope, C: ColumnMode = ColumnExpr> {
    #[column(primary_key, auto_increment, db_type = "integer")]
    id: C::Type<'scope, i32>,
}

#[allow(dead_code)]
#[derive(Schema)]
struct Public {
    users: User<'static, ColumnName>,
}

#[test]
fn test_select_uses_question_mark_placeholders() {
    let users = TestConnection.select(|q| {
        let user = q.from::<User>();
        q.where_(user.id.equals(1));
        q.returning(&user.id + 2)
    });

    assert_eq!(
        users.to_sql(),
        "SELECT (q0_0.id + ?) AS expr FROM public.users AS q0_0 WHERE (q0_0.id = ?)"
    );
    assert_eq!(users.params(), vec![BindValue::Int(2), BindValue::Int(1)]);
}

#[test]
fn test_select_numbers_nothing_across_subqueries() {
    let inner = TestConnection.select(|q| {
        let user = q.from::<User>();
        q.where_(user.name.equals("Ada"));
        q.returning(user.id + 1)
    });
    let outer = TestConnection.select(|q| {
        let user_id = q.q(&inner);
        q.where_(user_id.equals(3));
        q.returning(&user_id + 4)
    });

    assert_eq!(
        outer.to_sql(),
        "SELECT (q0_0.expr + ?) AS expr FROM (SELECT (q0_0.id + ?) AS expr FROM public.users AS q0_0 WHERE (q0_0.name = ?)) AS q0_0 WHERE (q0_0.expr = ?)"
    );
    assert_eq!(
        outer.params(),
        vec![
            BindValue::Int(4),
            BindValue::Int(1),
            BindValue::Text("Ada".to_owned()),
            BindValue::Int(3),
        ]
    );
}

#[test]
fn test_insert_update_and_delete_render_returning() {
    let insert = TestConnection
        .insert::<User>()
        .name("Ada")
        .returning(|user| user.id);
    let update = TestConnection
        .update::<User>()
        .name("Ada")
        .where_(|user| user.id.equals(1))
        .returning(|user| (user.id, user.name));
    let delete = TestConnection
        .delete::<User>()
        .where_(|user| user.id.equals(1))
        .returning(|user| user);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO public.users (name) VALUES (?) RETURNING q0_0.id AS id"
    );
    assert_eq!(
        update.to_sql(),
        "UPDATE public.users AS q0_0 SET name = ? WHERE (q0_0.id = ?) RETURNING q0_0.id AS t0_id, q0_0.name AS t1_name"
    );
    assert_eq!(
        delete.to_sql(),
        "DELETE FROM public.users AS q0_0 WHERE (q0_0.id = ?) RETURNING q0_0.id AS id, q0_0.name AS name"
    );
    assert_eq!(insert.params(), vec![BindValue::Text("Ada".to_owned())]);
    assert_eq!(
        update.params(),
        vec![BindValue::Text("Ada".to_owned()), BindValue::Int(1)]
    );
    assert_eq!(delete.params(), vec![BindValue::Int(1)]);
}

#[test]
fn test_insert_can_use_default_values() {
    let insert = TestConnection
        .insert::<DefaultedRecord>()
        .returning(|record| record.id);

    assert_eq!(
        insert.to_sql(),
        "INSERT INTO defaulted_records DEFAULT VALUES RETURNING q0_0.id AS id"
    );
    assert_eq!(insert.params(), Vec::<BindValue>::new());
}

#[test]
fn test_backend_writes_table_ddl_with_autoincrement() {
    let mut sql = Vec::new();
    let tables = <Public as Schema>::tables().collect::<Vec<_>>();
    TestConnection.write_table(tables[0], &mut sql).unwrap();
    let sql = String::from_utf8(sql).unwrap();

    assert_eq!(
        sql,
        "CREATE TABLE public.users (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL)"
    );
}
