//! Common Table Expressions (`WITH name AS (<body>) …`).
//!
//! A CTE is a **view whose body is inlined** as a `WITH` prefix instead of persisted as a
//! `CREATE VIEW`: a named, read-only, parameter-free query result with typed columns. It is built on
//! the view plumbing ([`ModelConn`](crate::ModelConn) / [`ViewSelect`](crate::ViewSelect) /
//! [`ViewQueryModel`](crate::ViewQueryModel)) — `#[derive(CTE)]` generates the same queryable
//! projection as `#[derive(View)]`, plus the [`SchemaCte`] metadata below.
//!
//! It is **one-directional**: a CTE is never published (it has no `ViewDef`), and a view is never
//! inlined (it is not a [`CteDefinition`]).

use crate::{ModelConn, ViewColumnModel, ViewQueryModel, ViewSelect};

/// A CTE's declared output schema — its name and typed columns. The CTE analogue of
/// [`SchemaView`](crate::SchemaView), generated by `#[derive(CTE)]`.
pub trait SchemaCte {
    /// The declared output row type (the ordered column types), matched against the body's projection.
    type Row;

    /// The CTE's name, used as the `WITH` binding and the `FROM` reference.
    fn cte_name() -> &'static str;

    /// The declared output columns (name + type + nullability).
    fn cte_columns() -> Vec<ViewColumnModel>;
}

/// The user-written body of a CTE: the `SELECT` that produces its declared columns, built against the
/// render-only [`ModelConn`] (parameter-free, like a view body). The metadata comes from [`SchemaCte`]
/// (generated by `#[derive(CTE)]`), so the user writes only [`definition`](Self::definition).
///
/// The `impl ViewSelect<Row = <Self as SchemaCte>::Row>` return type is the compile-time guarantee
/// that the body's projection decodes to exactly the declared columns.
pub trait CteDefinition: SchemaCte {
    /// The CTE body, built against the render-only connection (fully owned, no caller lifetime).
    fn definition(db: &'static ModelConn) -> impl ViewSelect<Row = <Self as SchemaCte>::Row>;
}

/// Object-safe view of a CTE used while collecting a query's `WITH` clause: its name and lowered body.
///
/// (A CTE body that references *another* CTE — transitive dependencies + topological ordering — is a
/// later increment; this carries just the name and body for the flat case.)
pub trait CteDef: Sync {
    fn name(&self) -> &'static str;

    /// A stable per-CTE-type identity, used to de-duplicate a CTE referenced from several sources into
    /// one `WITH` entry and to distinguish that from a genuine name collision between two *distinct*
    /// CTEs. A [`TypeId`](std::any::TypeId) rather than the marker's address: the markers are
    /// zero-sized, and distinct ZST statics are *not* guaranteed distinct addresses.
    fn type_key(&self) -> std::any::TypeId;

    /// The CTE's declared output columns, rendered as the explicit `WITH name (col, …) AS (…)` column
    /// list. Naming the columns explicitly decouples the body's projection aliases from the names the
    /// referencing query uses, so a tuple-projected body still exposes the declared column names.
    fn columns(&self) -> Vec<ViewColumnModel>;

    fn body_model(&self) -> ViewQueryModel;

    /// The CTEs this CTE's body references *directly* (a nested CTE: a `WITH` body that selects from
    /// another CTE). The query's `WITH` collector recurses through these to the transitive closure and
    /// emits every CTE in dependency order (a referenced CTE before the one that uses it). A flat CTE
    /// (body over base tables/views only) returns an empty list.
    fn cte_dependencies(&self) -> Vec<&'static dyn CteDef>;
}

/// Any [`CteDefinition`] is an object-safe [`CteDef`] the `WITH` collector can consume from its type
/// alone. Mirrors the `ViewDef` shim for views.
impl<T> CteDef for T
where
    T: CteDefinition + Sync + 'static,
{
    fn name(&self) -> &'static str {
        <T as SchemaCte>::cte_name()
    }

    fn type_key(&self) -> std::any::TypeId {
        std::any::TypeId::of::<T>()
    }

    fn columns(&self) -> Vec<ViewColumnModel> {
        <T as SchemaCte>::cte_columns()
    }

    fn body_model(&self) -> ViewQueryModel {
        cte_definition_model::<T>()
    }

    fn cte_dependencies(&self) -> Vec<&'static dyn CteDef> {
        cte_definition_dependencies::<T>()
    }
}

/// Lowers a [`CteDefinition`] type's body into the neutral model without needing an instance. Mirrors
/// [`view_definition_model`](crate::view_definition_model).
pub fn cte_definition_model<T>() -> ViewQueryModel
where
    T: CteDefinition,
{
    static MODEL_CONN: ModelConn = ModelConn;
    T::definition(&MODEL_CONN).lower()
}

/// The CTEs a [`CteDefinition`] type's body references directly, from its type alone — the
/// dependency edges the `WITH` collector follows for nested CTEs. Mirrors [`cte_definition_model`].
pub fn cte_definition_dependencies<T>() -> Vec<&'static dyn CteDef>
where
    T: CteDefinition,
{
    static MODEL_CONN: ModelConn = ModelConn;
    T::definition(&MODEL_CONN).cte_dependencies()
}
