/// A fixed homogeneous list used by core builders.
pub trait FixedList<T> {
    fn len(&self) -> usize;

    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    fn try_for_each<E>(&self, f: impl FnMut(&T) -> Result<(), E>) -> Result<(), E>;
}

/// Append an item to a typed list, producing the widened list type.
pub trait TupleAppend<T>: FixedList<T> + Sized {
    type Output: FixedList<T>;

    fn append(self, value: T) -> Self::Output;
}

/// Concatenate two typed lists.
pub trait TupleConcat<T, Rhs>: FixedList<T> + Sized
where
    Rhs: FixedList<T>,
{
    type Output: FixedList<T>;

    fn concat(self, rhs: Rhs) -> Self::Output;
}

/// Map a typed homogeneous list to another typed homogeneous list of the same width.
pub trait MapFixedList<T, U>: FixedList<T> + Sized {
    type Output: FixedList<U>;

    fn map_list(self, f: impl FnMut(T) -> U) -> Self::Output;
}

/// Empty heterogeneous list.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HNil;

/// Non-empty heterogeneous list.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HCons<Head, Tail> {
    pub head: Head,
    pub tail: Tail,
}

/// A heterogeneous list whose width is known in the type system.
pub trait HList {
    const LEN: usize;
}

/// Marker for query ASTs that contain no runtime parameters.
///
/// Execution APIs require this marker, so queries containing `param::<T>()`
/// must be prepared before values are supplied.
pub trait NoRuntimeParams: HList {}

/// Append a value to the end of a heterogeneous list.
pub trait PushBack<T>: HList + Sized {
    type Output: HList;

    fn push_back(self, value: T) -> Self::Output;
}

/// Concatenate two heterogeneous lists.
pub trait HAppend<Rhs>: HList + Sized
where
    Rhs: HList,
{
    type Output: HList;
}

/// Convert a heterogeneous list to a same-order tuple.
pub trait ToTuple {
    type Tuple;

    fn to_tuple(self) -> Self::Tuple;
}

/// Nullable-wrap an accumulated source-exprs list (each element a table's exprs struct) when building
/// a `RIGHT`/`FULL JOIN`, where the base columns become nullable. Per-table impls are generated by the
/// `Table` derive (mapping each `ColumnRef<K>` to `ColumnRef<Nullable<K>>`, and treating an
/// already-nullable exprs struct as idempotent); these `HList` impls thread it element-wise.
pub trait IntoNullableExprs {
    type Output;

    fn into_nullable_exprs(self) -> Self::Output;
}

impl IntoNullableExprs for HNil {
    type Output = HNil;

    fn into_nullable_exprs(self) -> Self::Output {
        self
    }
}

impl<Head, Tail> IntoNullableExprs for HCons<Head, Tail>
where
    Head: IntoNullableExprs,
    Tail: IntoNullableExprs,
{
    type Output = HCons<Head::Output, Tail::Output>;

    fn into_nullable_exprs(self) -> Self::Output {
        HCons {
            head: self.head.into_nullable_exprs(),
            tail: self.tail.into_nullable_exprs(),
        }
    }
}

/// Runtime values supplied when executing a prepared statement.
///
/// Parameterized by the backend `B` (mirroring how the row type is `Decode<B>`) so that
/// each supplied value can be encoded via [`Encode<B>`](crate::Encode) directly into the
/// backend's [`ParamWriter`](crate::ParamWriter), with no neutral intermediate.
pub trait PreparedParamValues<Shape, B>
where
    Shape: HList,
    B: crate::Backend,
{
    fn write_params(&self, writer: &mut B::ParamWriter<'_>) -> Result<(), B::Error>;

    fn write_param_at(
        &self,
        index: usize,
        writer: &mut B::ParamWriter<'_>,
    ) -> Result<bool, B::Error>;
}

/// Coerces a value supplied to a prepared statement into its runtime-parameter shape
/// entry type, which the backend then encodes via [`Encode`](crate::Encode).
///
/// This carries the type-level check that a supplied value is compatible with the
/// query's declared parameter type (e.g. `&str` for a `String` parameter), and performs
/// any owning conversion that requires. The resulting value is encoded by the backend.
pub trait IntoPreparedParam<T> {
    fn into_prepared_param(self) -> T;
}

/// Reflexive identity: any value can be supplied for a parameter of its own type.
///
/// This is what keeps the open codec usable for prepared *runtime* parameters, not just inline
/// literals: a custom type that implements [`Encode<B>`](crate::Encode) — for example a derived
/// newtype over `uuid::Uuid`, or a backend's `Json<T>` wrapper — can be passed to `param::<T>()`
/// with no extra impl. The convenience borrow conversions below (`&str` → `String`, etc.) cover the
/// non-reflexive cases and do not overlap, since their `Self` and target types differ.
impl<T> IntoPreparedParam<T> for T {
    fn into_prepared_param(self) -> T {
        self
    }
}

impl IntoPreparedParam<String> for &str {
    fn into_prepared_param(self) -> String {
        self.to_owned()
    }
}

impl IntoPreparedParam<String> for &String {
    fn into_prepared_param(self) -> String {
        self.clone()
    }
}

impl IntoPreparedParam<Option<String>> for Option<&str> {
    fn into_prepared_param(self) -> Option<String> {
        self.map(str::to_owned)
    }
}

impl IntoPreparedParam<Option<String>> for Option<&String> {
    fn into_prepared_param(self) -> Option<String> {
        self.cloned()
    }
}

impl<T> FixedList<T> for () {
    fn len(&self) -> usize {
        0
    }

    fn try_for_each<E>(&self, _f: impl FnMut(&T) -> Result<(), E>) -> Result<(), E> {
        Ok(())
    }
}

impl<T> TupleAppend<T> for () {
    type Output = (T,);

    fn append(self, value: T) -> Self::Output {
        (value,)
    }
}

impl<T, Rhs> TupleConcat<T, Rhs> for ()
where
    Rhs: FixedList<T>,
{
    type Output = Rhs;

    fn concat(self, rhs: Rhs) -> Self::Output {
        rhs
    }
}

impl<T, U> MapFixedList<T, U> for () {
    type Output = ();

    fn map_list(self, _f: impl FnMut(T) -> U) -> Self::Output {}
}

impl HList for HNil {
    const LEN: usize = 0;
}

impl NoRuntimeParams for HNil {}

impl<Head, Tail> HList for HCons<Head, Tail>
where
    Tail: HList,
{
    const LEN: usize = Tail::LEN + 1;
}

impl<T> PushBack<T> for HNil {
    type Output = HCons<T, HNil>;

    fn push_back(self, value: T) -> Self::Output {
        HCons {
            head: value,
            tail: HNil,
        }
    }
}

impl<Rhs> HAppend<Rhs> for HNil
where
    Rhs: HList,
{
    type Output = Rhs;
}

impl<Head, Tail, Rhs> HAppend<Rhs> for HCons<Head, Tail>
where
    Tail: HAppend<Rhs>,
    Rhs: HList,
{
    type Output = HCons<Head, <Tail as HAppend<Rhs>>::Output>;
}

impl<Head, Tail, T> PushBack<T> for HCons<Head, Tail>
where
    Tail: PushBack<T>,
{
    type Output = HCons<Head, <Tail as PushBack<T>>::Output>;

    fn push_back(self, value: T) -> Self::Output {
        HCons {
            head: self.head,
            tail: self.tail.push_back(value),
        }
    }
}

impl ToTuple for HNil {
    type Tuple = ();

    fn to_tuple(self) -> Self::Tuple {}
}

impl<B> PreparedParamValues<HNil, B> for ()
where
    B: crate::Backend,
{
    fn write_params(&self, _writer: &mut B::ParamWriter<'_>) -> Result<(), B::Error> {
        Ok(())
    }

    fn write_param_at(
        &self,
        _index: usize,
        _writer: &mut B::ParamWriter<'_>,
    ) -> Result<bool, B::Error> {
        Ok(false)
    }
}

squealy_macros::tuple_fixed_lists!(32);
squealy_macros::hlist_tuples!(32);
squealy_macros::prepared_param_values!(32);
