//! Owned, backend-neutral schema model.
//!
//! The compile-time `#[derive(Table/Schema/Database)]` types are the source of truth.
//! [`DatabaseModel::from_database`] materializes them into an owned model that DDL-management
//! operations (render create-from-scratch, package export/import, future diff) all consume. The same
//! model can later be produced from a package or from live-database introspection, so operations stay
//! source-agnostic.
//!
//! These types live in the core crate (rather than the `squealy-model` engine) so that backends can
//! implement [`SchemaBackend`](crate::SchemaBackend) against them without depending on the engine.
//! See `docs/ddl-management.md` for the design.

use crate::{
    AggregateFunc, ArithmeticOp, Column, ColumnDefault, ColumnType, CompareOp, Database,
    DatabaseSchema, ForeignKey, Index, OrderDirection, Table, WindowFunc,
};

/// An owned, backend-neutral model of a whole database.
#[derive(Clone, Debug, PartialEq)]
pub struct DatabaseModel {
    pub schemas: Vec<SchemaModel>,
}

/// A namespace within a database (a SQL "schema").
#[derive(Clone, Debug, Default, PartialEq)]
pub struct SchemaModel {
    /// The namespace name, or `None` for the default/unqualified namespace.
    pub name: Option<String>,
    pub tables: Vec<TableModel>,
    /// Views declared in this namespace. A view is a named `SELECT` with a typed output schema and a
    /// backend-neutral structural body; see [`ViewModel`].
    pub views: Vec<ViewModel>,
}

/// A table and its table-level, named constraints.
///
/// Unlike the query-side [`Column`] trait (which hangs primary-key/unique/foreign-key/check facts off
/// each column), the model hoists those into named table-level lists. This matches `ALTER TABLE … ADD
/// CONSTRAINT`, how catalogs report constraints during introspection, and admits composite keys.
#[derive(Clone, Debug, PartialEq)]
pub struct TableModel {
    pub name: String,
    pub comment: Option<String>,
    pub columns: Vec<ColumnModel>,
    pub primary_key: Option<Constraint>,
    pub foreign_keys: Vec<ForeignKeyModel>,
    pub uniques: Vec<Constraint>,
    pub checks: Vec<CheckModel>,
    pub indexes: Vec<IndexModel>,
}

/// Per-column facts (the table-level constraints live on [`TableModel`]).
#[derive(Clone, Debug, PartialEq)]
pub struct ColumnModel {
    pub name: String,
    pub comment: Option<String>,
    pub ty: SqlType,
    pub collation: Option<String>,
    pub nullable: bool,
    pub default: Option<DefaultValue>,
    pub identity: Option<IdentityModel>,
    pub generated: Option<GeneratedColumnModel>,
}

/// Backend-neutral identity / auto-increment metadata.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IdentityModel {
    pub mode: IdentityMode,
}

/// How a backend should generate identity values.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum IdentityMode {
    /// PostgreSQL-style `GENERATED ALWAYS AS IDENTITY`.
    Always,
    /// PostgreSQL-style `GENERATED BY DEFAULT AS IDENTITY`.
    ByDefault,
    /// MySQL-style `AUTO_INCREMENT`.
    AutoIncrement,
}

/// Backend-neutral generated-column metadata.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedColumnModel {
    pub expression: String,
    pub storage: GeneratedStorage,
}

/// Storage mode for a generated column.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GeneratedStorage {
    Virtual,
    Stored,
    Unknown,
}

/// The owned, backend-neutral logical column type.
///
/// This mirrors the compile-time [`ColumnType`] but owns its strings, so a model can be rebuilt from
/// a package or live-database introspection (the `const`-friendly [`ColumnType`] borrows `'static`
/// strings and cannot represent runtime-sourced values). It is the place the neutral type vocabulary
/// grows structurally (e.g. `Varchar { len }`) as introspection lands.
#[derive(Clone, Debug, PartialEq)]
pub enum SqlType {
    I8,
    I16,
    I32,
    I64,
    I128,
    Isize,
    U8,
    U16,
    U32,
    U64,
    U128,
    Usize,
    F32,
    F64,
    String,
    Bool,
    Varchar(u32),
    Char(u32),
    Text,
    Decimal {
        precision: u32,
        scale: u32,
    },
    Date,
    Time {
        tz: bool,
    },
    Timestamp {
        tz: bool,
    },
    Uuid,
    Json,
    Jsonb,
    Bytes,
    /// A backend-specific type name, emitted verbatim into DDL.
    Raw(String),
}

impl From<ColumnType> for SqlType {
    fn from(column_type: ColumnType) -> Self {
        match column_type {
            ColumnType::I8 => SqlType::I8,
            ColumnType::I16 => SqlType::I16,
            ColumnType::I32 => SqlType::I32,
            ColumnType::I64 => SqlType::I64,
            ColumnType::I128 => SqlType::I128,
            ColumnType::Isize => SqlType::Isize,
            ColumnType::U8 => SqlType::U8,
            ColumnType::U16 => SqlType::U16,
            ColumnType::U32 => SqlType::U32,
            ColumnType::U64 => SqlType::U64,
            ColumnType::U128 => SqlType::U128,
            ColumnType::Usize => SqlType::Usize,
            ColumnType::F32 => SqlType::F32,
            ColumnType::F64 => SqlType::F64,
            ColumnType::String => SqlType::String,
            ColumnType::Bool => SqlType::Bool,
            ColumnType::Varchar(length) => SqlType::Varchar(length),
            ColumnType::Char(length) => SqlType::Char(length),
            ColumnType::Text => SqlType::Text,
            ColumnType::Decimal { precision, scale } => SqlType::Decimal { precision, scale },
            ColumnType::Date => SqlType::Date,
            ColumnType::Time { tz } => SqlType::Time { tz },
            ColumnType::Timestamp { tz } => SqlType::Timestamp { tz },
            ColumnType::Uuid => SqlType::Uuid,
            ColumnType::Json => SqlType::Json,
            ColumnType::Jsonb => SqlType::Jsonb,
            ColumnType::Bytes => SqlType::Bytes,
            ColumnType::Raw(raw) => SqlType::Raw(raw.to_owned()),
        }
    }
}

/// The owned, backend-neutral mirror of [`ColumnDefault`] (owns its strings; see [`SqlType`]).
#[derive(Clone, Debug, PartialEq)]
pub enum DefaultValue {
    Null,
    Int(i128),
    UInt(u128),
    Float(f64),
    Text(String),
    Bool(bool),
    CurrentTimestamp,
    CurrentDate,
    CurrentTime,
    /// A backend-specific default expression, emitted verbatim into DDL.
    Raw(String),
}

impl From<ColumnDefault> for DefaultValue {
    fn from(default: ColumnDefault) -> Self {
        match default {
            ColumnDefault::Null => DefaultValue::Null,
            ColumnDefault::Int(value) => DefaultValue::Int(value),
            ColumnDefault::UInt(value) => DefaultValue::UInt(value),
            ColumnDefault::Float(value) => DefaultValue::Float(value),
            ColumnDefault::Text(value) => DefaultValue::Text(value.to_owned()),
            ColumnDefault::Bool(value) => DefaultValue::Bool(value),
            ColumnDefault::CurrentTimestamp => DefaultValue::CurrentTimestamp,
            ColumnDefault::CurrentDate => DefaultValue::CurrentDate,
            ColumnDefault::CurrentTime => DefaultValue::CurrentTime,
            ColumnDefault::Raw(value) => DefaultValue::Raw(value.to_owned()),
        }
    }
}

/// A named constraint over one or more columns (primary key, unique).
#[derive(Clone, Debug, PartialEq)]
pub struct Constraint {
    pub name: String,
    pub columns: Vec<String>,
}

/// A named foreign-key constraint.
#[derive(Clone, Debug, PartialEq)]
pub struct ForeignKeyModel {
    pub name: String,
    pub columns: Vec<String>,
    pub references_schema: Option<String>,
    pub references_table: String,
    pub references_columns: Vec<String>,
    pub match_type: Option<ForeignKeyMatch>,
    pub deferrability: Option<ConstraintDeferrability>,
    pub validation: Option<ConstraintValidation>,
    pub enforcement: Option<ConstraintEnforcement>,
    pub on_delete: Option<ForeignKeyAction>,
    pub on_update: Option<ForeignKeyAction>,
}

/// Whether a constraint has been validated against existing data.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ConstraintValidation {
    Validated,
    NotValidated,
    /// A backend-specific validation state.
    Raw(String),
}

impl ConstraintValidation {
    pub fn from_sql(validation: &str) -> Self {
        let normalized = validation
            .trim()
            .to_ascii_lowercase()
            .replace(['-', '_'], " ");
        match normalized.as_str() {
            "validated" | "valid" => ConstraintValidation::Validated,
            "not validated" | "not valid" => ConstraintValidation::NotValidated,
            _ => ConstraintValidation::Raw(validation.to_owned()),
        }
    }

    pub fn as_sql(&self) -> &str {
        match self {
            ConstraintValidation::Validated => "VALID",
            ConstraintValidation::NotValidated => "NOT VALID",
            ConstraintValidation::Raw(validation) => validation,
        }
    }
}

/// Whether a constraint is actively enforced for writes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ConstraintEnforcement {
    Enforced,
    NotEnforced,
    /// A backend-specific enforcement state.
    Raw(String),
}

impl ConstraintEnforcement {
    pub fn from_sql(enforcement: &str) -> Self {
        let normalized = enforcement
            .trim()
            .to_ascii_lowercase()
            .replace(['-', '_'], " ");
        match normalized.as_str() {
            "enforced" => ConstraintEnforcement::Enforced,
            "not enforced" => ConstraintEnforcement::NotEnforced,
            _ => ConstraintEnforcement::Raw(enforcement.to_owned()),
        }
    }

    pub fn as_sql(&self) -> &str {
        match self {
            ConstraintEnforcement::Enforced => "ENFORCED",
            ConstraintEnforcement::NotEnforced => "NOT ENFORCED",
            ConstraintEnforcement::Raw(enforcement) => enforcement,
        }
    }
}

/// Backend-neutral constraint deferrability.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ConstraintDeferrability {
    InitiallyImmediate,
    InitiallyDeferred,
    /// A backend-specific deferrability clause, emitted verbatim into DDL.
    Raw(String),
}

impl ConstraintDeferrability {
    pub fn from_sql(deferrability: &str) -> Self {
        let normalized = deferrability
            .trim()
            .to_ascii_lowercase()
            .replace(['-', '_'], " ");
        match normalized.as_str() {
            "initially immediate" | "deferrable initially immediate" => {
                ConstraintDeferrability::InitiallyImmediate
            }
            "initially deferred" | "deferrable initially deferred" => {
                ConstraintDeferrability::InitiallyDeferred
            }
            _ => ConstraintDeferrability::Raw(deferrability.to_owned()),
        }
    }

    pub fn as_sql(&self) -> &str {
        match self {
            ConstraintDeferrability::InitiallyImmediate => "DEFERRABLE INITIALLY IMMEDIATE",
            ConstraintDeferrability::InitiallyDeferred => "DEFERRABLE INITIALLY DEFERRED",
            ConstraintDeferrability::Raw(deferrability) => deferrability,
        }
    }
}

/// Backend-neutral foreign-key match type.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ForeignKeyMatch {
    Simple,
    Partial,
    Full,
    /// A backend-specific match type, emitted verbatim into DDL.
    Raw(String),
}

impl ForeignKeyMatch {
    pub fn from_sql(match_type: &str) -> Self {
        match match_type.trim().to_ascii_lowercase().as_str() {
            "simple" => ForeignKeyMatch::Simple,
            "partial" => ForeignKeyMatch::Partial,
            "full" => ForeignKeyMatch::Full,
            _ => ForeignKeyMatch::Raw(match_type.to_owned()),
        }
    }

    pub fn as_sql(&self) -> &str {
        match self {
            ForeignKeyMatch::Simple => "SIMPLE",
            ForeignKeyMatch::Partial => "PARTIAL",
            ForeignKeyMatch::Full => "FULL",
            ForeignKeyMatch::Raw(match_type) => match_type,
        }
    }
}

/// Backend-neutral referential action for a foreign key.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ForeignKeyAction {
    NoAction,
    Restrict,
    Cascade,
    SetNull,
    SetDefault,
    /// A backend-specific action, emitted verbatim into DDL.
    Raw(String),
}

impl ForeignKeyAction {
    pub fn from_sql(action: &str) -> Self {
        let normalized = action.trim().to_ascii_lowercase().replace(['-', '_'], " ");
        match normalized.as_str() {
            "no action" => ForeignKeyAction::NoAction,
            "restrict" => ForeignKeyAction::Restrict,
            "cascade" => ForeignKeyAction::Cascade,
            "set null" => ForeignKeyAction::SetNull,
            "set default" => ForeignKeyAction::SetDefault,
            _ => ForeignKeyAction::Raw(action.to_owned()),
        }
    }

    pub fn as_sql(&self) -> &str {
        match self {
            ForeignKeyAction::NoAction => "NO ACTION",
            ForeignKeyAction::Restrict => "RESTRICT",
            ForeignKeyAction::Cascade => "CASCADE",
            ForeignKeyAction::SetNull => "SET NULL",
            ForeignKeyAction::SetDefault => "SET DEFAULT",
            ForeignKeyAction::Raw(action) => action,
        }
    }
}

/// A named check constraint carrying a backend-specific boolean expression.
#[derive(Clone, Debug, PartialEq)]
pub struct CheckModel {
    pub name: String,
    pub expression: String,
    pub validation: Option<ConstraintValidation>,
    pub enforcement: Option<ConstraintEnforcement>,
}

/// A named index.
#[derive(Clone, Debug, PartialEq)]
pub struct IndexModel {
    pub name: String,
    /// Quoted column terms in the index key.
    pub columns: Vec<String>,
    /// Backend-specific expression terms in the index key, emitted verbatim.
    pub expressions: Vec<String>,
    /// Non-key columns stored with a covering index.
    pub include_columns: Vec<String>,
    pub unique: bool,
    pub method: Option<IndexMethod>,
    pub directions: Vec<IndexDirection>,
    pub nulls: Vec<IndexNullsOrder>,
    /// Backend-specific collations by zero-based key-term position.
    pub collations: Vec<IndexCollation>,
    /// Backend-specific operator classes by zero-based key-term position.
    pub operator_classes: Vec<IndexOperatorClass>,
    /// Backend-specific predicate for a partial index.
    pub predicate: Option<String>,
}

/// Sort direction for an indexed column.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum IndexDirection {
    Asc,
    Desc,
}

/// Null ordering for an indexed key term.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum IndexNullsOrder {
    First,
    Last,
}

/// Collation override for an indexed key term.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IndexCollation {
    pub position: usize,
    pub name: String,
}

/// Operator class override for an indexed key term.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IndexOperatorClass {
    pub position: usize,
    pub name: String,
}

/// Backend-neutral index access method.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum IndexMethod {
    BTree,
    Hash,
    Gin,
    Gist,
    SpGist,
    Brin,
    /// A backend-specific index method, emitted verbatim into DDL.
    Raw(String),
}

impl IndexMethod {
    pub fn from_sql(method: &str) -> Self {
        match method.trim().to_ascii_lowercase().as_str() {
            "btree" => IndexMethod::BTree,
            "hash" => IndexMethod::Hash,
            "gin" => IndexMethod::Gin,
            "gist" => IndexMethod::Gist,
            "spgist" => IndexMethod::SpGist,
            "brin" => IndexMethod::Brin,
            _ => IndexMethod::Raw(method.to_owned()),
        }
    }

    pub fn postgres_sql(&self) -> &str {
        match self {
            IndexMethod::BTree => "btree",
            IndexMethod::Hash => "hash",
            IndexMethod::Gin => "gin",
            IndexMethod::Gist => "gist",
            IndexMethod::SpGist => "spgist",
            IndexMethod::Brin => "brin",
            IndexMethod::Raw(method) => method,
        }
    }

    pub fn mysql_sql(&self) -> &str {
        match self {
            IndexMethod::BTree => "BTREE",
            IndexMethod::Hash => "HASH",
            IndexMethod::Gin => "GIN",
            IndexMethod::Gist => "GIST",
            IndexMethod::SpGist => "SPGIST",
            IndexMethod::Brin => "BRIN",
            IndexMethod::Raw(method) => method,
        }
    }
}

/// A view: a named `SELECT` with a typed output schema and a backend-neutral structural body.
///
/// The compile-time `#[derive(View)]` type is the source of truth; the walker materializes it here so
/// the same DDL-management operations (render, package export/import, future diff) that consume
/// [`TableModel`] also consume views. The body is structural ([`ViewQueryModel`]) so each backend
/// renders its own dialect and the model round-trips through a package.
#[derive(Clone, Debug, PartialEq)]
pub struct ViewModel {
    pub name: String,
    pub comment: Option<String>,
    /// The view's output columns, in projection order. Powers DDL (the optional column list),
    /// packaging, introspection, and the queryable typed face.
    pub columns: Vec<ViewColumnModel>,
    /// The structural body of the view's `SELECT`.
    pub query: ViewQueryModel,
}

/// One output column of a [`ViewModel`].
#[derive(Clone, Debug, PartialEq)]
pub struct ViewColumnModel {
    pub name: String,
    pub ty: SqlType,
    pub nullable: bool,
}

/// The backend-neutral structural body of a view's `SELECT`.
///
/// Source/join/projection structure and the inner scalar expressions (predicate bodies, projection
/// expressions, group/having/order keys) are all captured structurally as [`ExprNode`] trees, so each
/// backend renders them in its own dialect. Literals are inlined (a view body carries no bind
/// parameters).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ViewQueryModel {
    /// Whether the view body is `SELECT DISTINCT`.
    pub distinct: bool,
    pub projection: Vec<ProjectionItem>,
    pub from: Option<SourceRef>,
    pub joins: Vec<JoinItem>,
    pub filter: Option<ExprNode>,
    pub group_by: Vec<ExprNode>,
    pub having: Option<ExprNode>,
    pub order_by: Vec<OrderItem>,
    pub limit: Option<usize>,
    pub offset: Option<usize>,
}

/// One projected output expression together with its output column name.
#[derive(Clone, Debug, PartialEq)]
pub struct ProjectionItem {
    pub output_name: String,
    pub expr: ExprNode,
}

/// A table or view referenced in a view body, with the alias bound to it in the `SELECT`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SourceRef {
    pub schema: Option<String>,
    pub name: String,
    pub alias: String,
}

/// A join in a view body.
#[derive(Clone, Debug, PartialEq)]
pub struct JoinItem {
    pub kind: JoinKind,
    pub source: SourceRef,
    pub on: ExprNode,
}

/// The kind of join in a view body.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum JoinKind {
    Inner,
    Left,
    Right,
    Full,
}

/// One `ORDER BY` term in a view body.
#[derive(Clone, Debug, PartialEq)]
pub struct OrderItem {
    pub expr: ExprNode,
    pub direction: Option<OrderDirection>,
    pub nulls: Option<OrderNulls>,
}

/// Null ordering for an `ORDER BY` term.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OrderNulls {
    First,
    Last,
}

/// A backend-neutral SQL expression from a view body.
///
/// Stored structurally (rather than as pre-rendered text) so each backend renders it in its own
/// dialect — correct identifier quoting, cast type names, integer-division casts, and `LIKE`/`ILIKE`.
/// Literals are inlined, since a view body carries no bind parameters.
#[derive(Clone, Debug, PartialEq)]
pub enum ExprNode {
    /// A qualified column reference, rendered as `<alias>.<column>`.
    Column { alias: String, column: String },
    /// An inlined SQL literal, already formatted (e.g. `'Ada'`, `42`, `TRUE`, `NULL`).
    Literal(String),
    /// Binary arithmetic; `Divide` uses the backend's fractional-division handling.
    Binary {
        op: ArithmeticOp,
        left: Box<ExprNode>,
        right: Box<ExprNode>,
    },
    /// `CAST(<operand> AS <ty>)`, with the backend's spelling of `ty`.
    Cast { operand: Box<ExprNode>, ty: SqlType },
    /// An aggregate call `FUNC([DISTINCT] <operand>)`, optionally wrapped in a cast to `result` so the
    /// output column's wire type matches the view's declared column type.
    Aggregate {
        func: AggregateFunc,
        distinct: bool,
        operand: Box<ExprNode>,
        result: Option<SqlType>,
    },
    /// A comparison `<left> <op> <right>`.
    Compare {
        op: CompareOp,
        left: Box<ExprNode>,
        right: Box<ExprNode>,
    },
    /// A logical `AND`/`OR`.
    Logical {
        op: LogicalOp,
        left: Box<ExprNode>,
        right: Box<ExprNode>,
    },
    /// `NOT (<operand>)`.
    Not(Box<ExprNode>),
    /// `<operand> IS [NOT] NULL`.
    IsNull {
        negated: bool,
        operand: Box<ExprNode>,
    },
    /// `<operand> [NOT] LIKE <pattern>` (`ILIKE` for `case_insensitive` on supporting dialects).
    Like {
        case_insensitive: bool,
        negated: bool,
        operand: Box<ExprNode>,
        pattern: Box<ExprNode>,
    },
    /// `<operand> [NOT] IN (<items>)` against an inline value list.
    In {
        negated: bool,
        operand: Box<ExprNode>,
        items: Vec<ExprNode>,
    },
    /// `<operand> [NOT] BETWEEN <low> AND <high>`.
    Between {
        negated: bool,
        operand: Box<ExprNode>,
        low: Box<ExprNode>,
        high: Box<ExprNode>,
    },
    /// A scalar subquery `(SELECT …)` used as a value.
    ScalarSubquery(Box<ViewQueryModel>),
    /// `<operand> [NOT] IN (<subquery>)`.
    InSubquery {
        negated: bool,
        operand: Box<ExprNode>,
        subquery: Box<ViewQueryModel>,
    },
    /// `[NOT] EXISTS (<subquery>)`.
    Exists {
        negated: bool,
        subquery: Box<ViewQueryModel>,
    },
    /// A window function: `FUNC(<args>) OVER (PARTITION BY … ORDER BY …)`, optionally cast to `result`.
    Window {
        func: WindowFunc,
        args: Vec<ExprNode>,
        partition_by: Vec<ExprNode>,
        order_by: Vec<WindowOrderTerm>,
        result: Option<SqlType>,
    },
    /// Searched `CASE WHEN … THEN … [ELSE …] END`, optionally wrapped in `CAST(… AS result)` to pin
    /// the result type (so all-parameter branches stay typeable).
    Case {
        arms: Vec<CaseArm>,
        else_: Option<Box<ExprNode>>,
        result: Option<SqlType>,
    },
}

/// One `ORDER BY` term inside a window function's `OVER (…)` clause.
#[derive(Clone, Debug, PartialEq)]
pub struct WindowOrderTerm {
    pub expr: ExprNode,
    pub direction: OrderDirection,
}

/// One `WHEN <when> THEN <then>` arm of an [`ExprNode::Case`].
#[derive(Clone, Debug, PartialEq)]
pub struct CaseArm {
    pub when: Box<ExprNode>,
    pub then: Box<ExprNode>,
}

/// Conjunction/disjunction for [`ExprNode::Logical`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LogicalOp {
    And,
    Or,
}

/// Object-safe runtime metadata and body lowering for a view, consumed by the model walker.
///
/// The `#[derive(View)]` macro generates an implementation: the typed `ViewDefinition` the user writes
/// is lowered into [`Self::definition_model`] through the canonical model sink.
pub trait ViewDef: Sync {
    fn schema_name(&self) -> Option<&'static str>;

    fn name(&self) -> &'static str;

    /// The view's output columns, in projection order.
    fn columns(&self) -> Vec<ViewColumnModel>;

    /// The structural body of the view's `SELECT`, with literals inlined.
    fn definition_model(&self) -> ViewQueryModel;
}

impl ViewModel {
    /// The sources this view depends on, used to topologically order view creation. This walks the
    /// whole body — `FROM`/`JOIN`s and every expression, recursing into scalar/`IN`/`EXISTS`
    /// subqueries — so a view that references another view only inside a subquery is still ordered
    /// after it. Dependencies on tables are irrelevant to view ordering (all tables precede any view).
    pub fn referenced_sources(&self) -> impl Iterator<Item = &SourceRef> {
        let mut sources = Vec::new();
        collect_query_sources(&self.query, &mut sources);
        sources.into_iter()
    }
}

/// Collects every [`SourceRef`] reachable from a query body, recursing through subqueries.
fn collect_query_sources<'a>(query: &'a ViewQueryModel, sources: &mut Vec<&'a SourceRef>) {
    sources.extend(query.from.iter());
    for join in &query.joins {
        sources.push(&join.source);
        collect_expr_sources(&join.on, sources);
    }
    for item in &query.projection {
        collect_expr_sources(&item.expr, sources);
    }
    if let Some(filter) = &query.filter {
        collect_expr_sources(filter, sources);
    }
    for expr in &query.group_by {
        collect_expr_sources(expr, sources);
    }
    if let Some(having) = &query.having {
        collect_expr_sources(having, sources);
    }
    for order in &query.order_by {
        collect_expr_sources(&order.expr, sources);
    }
}

/// Collects every [`SourceRef`] reachable from an expression, recursing through nested subqueries.
fn collect_expr_sources<'a>(expr: &'a ExprNode, sources: &mut Vec<&'a SourceRef>) {
    match expr {
        ExprNode::Column { .. } | ExprNode::Literal(_) => {}
        ExprNode::Binary { left, right, .. }
        | ExprNode::Compare { left, right, .. }
        | ExprNode::Logical { left, right, .. } => {
            collect_expr_sources(left, sources);
            collect_expr_sources(right, sources);
        }
        ExprNode::Cast { operand, .. } | ExprNode::Aggregate { operand, .. } => {
            collect_expr_sources(operand, sources);
        }
        ExprNode::Not(operand) | ExprNode::IsNull { operand, .. } => {
            collect_expr_sources(operand, sources);
        }
        ExprNode::Like {
            operand, pattern, ..
        } => {
            collect_expr_sources(operand, sources);
            collect_expr_sources(pattern, sources);
        }
        ExprNode::In { operand, items, .. } => {
            collect_expr_sources(operand, sources);
            for item in items {
                collect_expr_sources(item, sources);
            }
        }
        ExprNode::Between {
            operand, low, high, ..
        } => {
            collect_expr_sources(operand, sources);
            collect_expr_sources(low, sources);
            collect_expr_sources(high, sources);
        }
        ExprNode::ScalarSubquery(subquery) | ExprNode::Exists { subquery, .. } => {
            collect_query_sources(subquery, sources);
        }
        ExprNode::InSubquery {
            operand, subquery, ..
        } => {
            collect_expr_sources(operand, sources);
            collect_query_sources(subquery, sources);
        }
        ExprNode::Window {
            args,
            partition_by,
            order_by,
            ..
        } => {
            for arg in args {
                collect_expr_sources(arg, sources);
            }
            for partition in partition_by {
                collect_expr_sources(partition, sources);
            }
            for order in order_by {
                collect_expr_sources(&order.expr, sources);
            }
        }
        ExprNode::Case { arms, else_, .. } => {
            for arm in arms {
                collect_expr_sources(&arm.when, sources);
                collect_expr_sources(&arm.then, sources);
            }
            if let Some(else_) = else_ {
                collect_expr_sources(else_, sources);
            }
        }
    }
}

impl DatabaseModel {
    /// Walks a compile-time [`Database`] into an owned model.
    pub fn from_database<D: Database>() -> Self {
        Self {
            schemas: D::schemas().map(schema_from_dyn).collect(),
        }
    }
}

fn schema_from_dyn(schema: &(dyn DatabaseSchema + Sync)) -> SchemaModel {
    SchemaModel {
        name: schema.name().map(str::to_owned),
        tables: schema.tables().map(table_from_dyn).collect(),
        views: schema.views().map(view_from_dyn).collect(),
    }
}

fn view_from_dyn(view: &(dyn crate::ViewDef + Sync)) -> ViewModel {
    ViewModel {
        name: view.name().to_owned(),
        comment: None,
        columns: view.columns(),
        query: view.definition_model(),
    }
}

fn table_from_dyn(table: &(dyn Table + Sync)) -> TableModel {
    let name = table.name().to_owned();
    let columns = table.columns();

    // Prefer an explicit table-level primary key (which carries column ordering and an optional
    // name); otherwise hoist every column marked `#[column(primary_key)]` into one constraint.
    let primary_key = match table.primary_key() {
        Some(pk) => Some(Constraint {
            name: pk.name.map(str::to_owned).unwrap_or_else(|| pk_name(&name)),
            columns: pk
                .columns
                .iter()
                .map(|column| (*column).to_owned())
                .collect(),
        }),
        None => {
            let pk_columns = columns
                .iter()
                .filter(|column| column.primary_key())
                .map(|column| column.name().to_owned())
                .collect::<Vec<_>>();
            (!pk_columns.is_empty()).then(|| Constraint {
                name: pk_name(&name),
                columns: pk_columns,
            })
        }
    };

    // Single-column `#[column(unique)]` markers, then table-level `#[unique(columns = [..])]`
    // composite constraints. The latter carry an optional explicit name and otherwise fall back to
    // the same deterministic `uq_<table>_<columns>` convention. A unique that carries a
    // `where = ...` predicate is excluded here: Postgres cannot attach a `WHERE` to a table
    // constraint, so it is lowered to a partial unique index below (sharing the `uq_` name).
    let uniques = columns
        .iter()
        .filter(|column| column.unique() && column.unique_predicate().is_none())
        .map(|column| Constraint {
            name: uq_name(&name, &[column.name()]),
            columns: vec![column.name().to_owned()],
        })
        .chain(
            table
                .uniques()
                .iter()
                .filter(|unique| unique.predicate.is_none())
                .map(|unique| Constraint {
                    name: unique
                        .name
                        .map(str::to_owned)
                        .unwrap_or_else(|| uq_name(&name, unique.columns)),
                    columns: unique
                        .columns
                        .iter()
                        .map(|column| (*column).to_owned())
                        .collect(),
                }),
        )
        .collect();

    let foreign_keys = columns
        .iter()
        .filter_map(|column| {
            column
                .references()
                .map(|reference| foreign_key_from_dyn(&name, column.name(), reference))
        })
        .collect();

    let checks = columns
        .iter()
        .filter_map(|column| {
            column.check().map(|expression| CheckModel {
                name: ck_name(&name, column.name()),
                expression: expression.to_owned(),
                validation: None,
                enforcement: None,
            })
        })
        .collect();

    // Predicated uniques (single-column `#[column(unique, where = ...)]` and table-level
    // `#[unique(columns = [..], where = ...)]`) become partial unique indexes, appended after the
    // table's own `#[index(..)]` declarations.
    let partial_unique_indexes = columns
        .iter()
        .filter_map(|column| {
            column.unique_predicate().map(|predicate| {
                partial_unique_index(
                    uq_name(&name, &[column.name()]),
                    vec![column.name().to_owned()],
                    predicate,
                )
            })
        })
        .chain(table.uniques().iter().filter_map(|unique| {
            unique.predicate.map(|predicate| {
                partial_unique_index(
                    unique
                        .name
                        .map(str::to_owned)
                        .unwrap_or_else(|| uq_name(&name, unique.columns)),
                    unique
                        .columns
                        .iter()
                        .map(|column| (*column).to_owned())
                        .collect(),
                    predicate,
                )
            })
        }));

    let indexes = table
        .indexes()
        .iter()
        .map(|index| index_from_dyn(&name, *index))
        .chain(partial_unique_indexes)
        .collect();

    TableModel {
        name,
        comment: None,
        columns: columns
            .iter()
            .map(|column| column_from_dyn(*column))
            .collect(),
        primary_key,
        foreign_keys,
        uniques,
        checks,
        indexes,
    }
}

fn column_from_dyn(column: &dyn Column) -> ColumnModel {
    ColumnModel {
        name: column.name().to_owned(),
        comment: None,
        ty: column.column_type().into(),
        collation: None,
        nullable: column.nullable(),
        default: column.default().map(DefaultValue::from),
        identity: column.auto_increment().then_some(IdentityModel {
            mode: IdentityMode::ByDefault,
        }),
        generated: column.generated().then_some(GeneratedColumnModel {
            expression: String::new(),
            storage: GeneratedStorage::Unknown,
        }),
    }
}

fn foreign_key_from_dyn(table: &str, column: &str, reference: &dyn ForeignKey) -> ForeignKeyModel {
    ForeignKeyModel {
        name: fk_name(table, &[column]),
        columns: vec![column.to_owned()],
        references_schema: reference.schema_name().map(str::to_owned),
        references_table: reference.table().to_owned(),
        references_columns: vec![reference.column().to_owned()],
        match_type: None,
        deferrability: None,
        validation: None,
        enforcement: None,
        on_delete: reference.on_delete().map(ForeignKeyAction::from_sql),
        on_update: reference.on_update().map(ForeignKeyAction::from_sql),
    }
}

fn index_from_dyn(table: &str, index: &dyn Index) -> IndexModel {
    let columns = index.columns();
    IndexModel {
        name: index
            .name()
            .map(str::to_owned)
            .unwrap_or_else(|| idx_name(table, columns)),
        columns: columns.iter().map(|column| (*column).to_owned()).collect(),
        expressions: Vec::new(),
        include_columns: Vec::new(),
        unique: index.unique(),
        method: None,
        directions: Vec::new(),
        nulls: Vec::new(),
        collations: Vec::new(),
        operator_classes: Vec::new(),
        predicate: index.predicate().map(|predicate| predicate()),
    }
}

/// A partial unique index synthesized from a predicated `#[column(unique, where = ...)]` or
/// `#[unique(columns = [..], where = ...)]` declaration. It keeps the `uq_<table>_<columns>`
/// identity of the constraint it replaces, but renders as `CREATE UNIQUE INDEX ... WHERE ...`.
fn partial_unique_index(
    name: String,
    columns: Vec<String>,
    predicate: fn() -> String,
) -> IndexModel {
    IndexModel {
        name,
        columns,
        expressions: Vec::new(),
        include_columns: Vec::new(),
        unique: true,
        method: None,
        directions: Vec::new(),
        nulls: Vec::new(),
        collations: Vec::new(),
        operator_classes: Vec::new(),
        predicate: Some(predicate()),
    }
}

// Deterministic constraint/index names. These double as the identity the future diff uses to match
// constraints across versions, so the conventions are stable and documented.

fn join_columns(columns: &[&str]) -> String {
    columns.join("_")
}

fn pk_name(table: &str) -> String {
    format!("pk_{table}")
}

fn uq_name(table: &str, columns: &[&str]) -> String {
    format!("uq_{table}_{}", join_columns(columns))
}

fn fk_name(table: &str, columns: &[&str]) -> String {
    format!("fk_{table}_{}", join_columns(columns))
}

fn ck_name(table: &str, column: &str) -> String {
    format!("ck_{table}_{column}")
}

fn idx_name(table: &str, columns: &[&str]) -> String {
    format!("idx_{table}_{}", join_columns(columns))
}

#[cfg(test)]
mod tests {
    use super::*;
    use squealy::*;

    #[derive(Clone, Debug, PartialEq, Table)]
    #[schema(Public)]
    struct User<'scope, C: ColumnMode = ColumnExpr> {
        #[column(primary_key, auto_increment)]
        id: C::Type<'scope, i32>,
        #[column(unique)]
        email: C::Type<'scope, String>,
        #[column(index)]
        name: C::Type<'scope, String>,
        #[column(db_type = "varchar(16)")]
        code: C::Type<'scope, String>,
        #[column(db_type = "jsonb")]
        payload: C::Type<'scope, String>,
    }

    #[derive(Clone, Debug, PartialEq, Table)]
    #[schema(Public)]
    struct Post<'scope, C: ColumnMode = ColumnExpr> {
        #[column(primary_key, auto_increment)]
        id: C::Type<'scope, i32>,
        #[column(references(User::id, on_delete = "cascade"))]
        user_id: C::Type<'scope, i32>,
        title: C::Type<'scope, String>,
    }

    #[allow(dead_code)]
    #[derive(Schema)]
    struct Public {
        users: User<'static, ColumnName>,
        posts: Post<'static, ColumnName>,
    }

    #[allow(dead_code)]
    #[derive(Database)]
    struct App {
        public: Public,
    }

    fn table<'a>(model: &'a DatabaseModel, name: &str) -> &'a TableModel {
        model.schemas[0]
            .tables
            .iter()
            .find(|table| table.name == name)
            .unwrap_or_else(|| panic!("table `{name}` not found"))
    }

    #[test]
    fn walks_schema_and_tables() {
        let model = DatabaseModel::from_database::<App>();

        assert_eq!(model.schemas.len(), 1);
        assert_eq!(model.schemas[0].name.as_deref(), Some("public"));
        assert_eq!(model.schemas[0].tables.len(), 2);
    }

    #[test]
    fn hoists_primary_key_unique_and_index() {
        let model = DatabaseModel::from_database::<App>();
        let users = table(&model, "users");

        assert_eq!(
            users.primary_key,
            Some(Constraint {
                name: "pk_users".to_owned(),
                columns: vec!["id".to_owned()],
            })
        );
        assert_eq!(
            users.uniques,
            vec![Constraint {
                name: "uq_users_email".to_owned(),
                columns: vec!["email".to_owned()],
            }]
        );
        // `#[column(index)]` on `name` surfaces as a table-level index.
        assert!(
            users
                .indexes
                .iter()
                .any(|index| index.columns == vec!["name".to_owned()]),
            "expected an index on `name`: {:?}",
            users.indexes
        );

        let id = &users.columns[0];
        assert_eq!(id.name, "id");
        assert_eq!(id.ty, SqlType::I32);
        assert_eq!(
            id.identity,
            Some(IdentityModel {
                mode: IdentityMode::ByDefault
            })
        );
        assert!(!id.nullable);
    }

    #[derive(Clone, Debug, PartialEq, Table)]
    #[schema(Public)]
    #[primary_key(columns = [tenant_id, id])]
    struct Membership<'scope, C: ColumnMode = ColumnExpr> {
        tenant_id: C::Type<'scope, i64>,
        id: C::Type<'scope, i64>,
        role: C::Type<'scope, String>,
    }

    #[derive(Clone, Debug, PartialEq, Table)]
    #[schema(Public)]
    #[primary_key(name = "membership_pk", columns = [tenant_id, id])]
    struct NamedMembership<'scope, C: ColumnMode = ColumnExpr> {
        tenant_id: C::Type<'scope, i64>,
        id: C::Type<'scope, i64>,
    }

    #[derive(Clone, Debug, PartialEq, Table)]
    #[schema(Public)]
    #[unique(columns = [organization_id, slug])]
    struct Repository<'scope, C: ColumnMode = ColumnExpr> {
        #[column(primary_key)]
        id: C::Type<'scope, i64>,
        organization_id: C::Type<'scope, i64>,
        slug: C::Type<'scope, String>,
    }

    #[derive(Clone, Debug, PartialEq, Table)]
    #[schema(Public)]
    #[unique(name = "uq_widget_sku", columns = [tenant_id, sku])]
    #[unique(columns = [tenant_id, label])]
    struct Widget<'scope, C: ColumnMode = ColumnExpr> {
        #[column(primary_key)]
        id: C::Type<'scope, i64>,
        #[column(unique)]
        tenant_id: C::Type<'scope, i64>,
        sku: C::Type<'scope, String>,
        label: C::Type<'scope, String>,
    }

    #[allow(dead_code)]
    #[derive(Schema)]
    struct CompositePublic {
        memberships: Membership<'static, ColumnName>,
        named_memberships: NamedMembership<'static, ColumnName>,
        repositorys: Repository<'static, ColumnName>,
        widgets: Widget<'static, ColumnName>,
    }

    #[allow(dead_code)]
    #[derive(Database)]
    struct CompositeApp {
        public: CompositePublic,
    }

    #[test]
    fn table_level_compound_primary_key_preserves_column_order() {
        let model = DatabaseModel::from_database::<CompositeApp>();
        let memberships = table(&model, "memberships");

        assert_eq!(
            memberships.primary_key,
            Some(Constraint {
                name: "pk_memberships".to_owned(),
                columns: vec!["tenant_id".to_owned(), "id".to_owned()],
            })
        );
    }

    #[test]
    fn table_level_primary_key_name_override_flows_through() {
        let model = DatabaseModel::from_database::<CompositeApp>();
        let named = table(&model, "named_memberships");

        assert_eq!(
            named.primary_key,
            Some(Constraint {
                name: "membership_pk".to_owned(),
                columns: vec!["tenant_id".to_owned(), "id".to_owned()],
            })
        );
    }

    #[test]
    fn table_level_composite_unique_emits_constraint() {
        let model = DatabaseModel::from_database::<CompositeApp>();
        let repository = table(&model, "repositorys");

        assert_eq!(
            repository.uniques,
            vec![Constraint {
                name: "uq_repositorys_organization_id_slug".to_owned(),
                columns: vec!["organization_id".to_owned(), "slug".to_owned()],
            }]
        );
    }

    #[test]
    fn table_level_unique_combines_column_marker_name_override_and_multiples() {
        let model = DatabaseModel::from_database::<CompositeApp>();
        let widget = table(&model, "widgets");

        // The single-column `#[column(unique)]` marker is hoisted first, then the two table-level
        // `#[unique(...)]` declarations in source order; the first carries an explicit name.
        assert_eq!(
            widget.uniques,
            vec![
                Constraint {
                    name: "uq_widgets_tenant_id".to_owned(),
                    columns: vec!["tenant_id".to_owned()],
                },
                Constraint {
                    name: "uq_widget_sku".to_owned(),
                    columns: vec!["tenant_id".to_owned(), "sku".to_owned()],
                },
                Constraint {
                    name: "uq_widgets_tenant_id_label".to_owned(),
                    columns: vec!["tenant_id".to_owned(), "label".to_owned()],
                },
            ]
        );
    }

    #[test]
    fn maps_db_type_columns_into_structured_sql_types() {
        // `#[column(db_type = "...")]` parses to a structured `ColumnType` in the derive, which the
        // walker carries through `From<ColumnType> for SqlType` into the owned model.
        let model = DatabaseModel::from_database::<App>();
        let users = table(&model, "users");

        let column = |name: &str| {
            users
                .columns
                .iter()
                .find(|column| column.name == name)
                .unwrap_or_else(|| panic!("column `{name}` not found"))
        };

        assert_eq!(column("code").ty, SqlType::Varchar(16));
        assert_eq!(column("payload").ty, SqlType::Jsonb);
    }

    #[test]
    fn hoists_foreign_key() {
        let model = DatabaseModel::from_database::<App>();
        let posts = table(&model, "posts");

        assert_eq!(
            posts.foreign_keys,
            vec![ForeignKeyModel {
                name: "fk_posts_user_id".to_owned(),
                columns: vec!["user_id".to_owned()],
                references_schema: Some("public".to_owned()),
                references_table: "users".to_owned(),
                references_columns: vec!["id".to_owned()],
                match_type: None,
                deferrability: None,
                validation: None,
                enforcement: None,
                on_delete: Some(ForeignKeyAction::Cascade),
                on_update: None,
            }]
        );
    }
}
